### ISSUE TITLE
Does this suite test for fullwidth less-than signs? (and greater)

### ISSUE THREAD

**Issue by digitalpacman** [s0md3v/XSStrike#101]
SQL Server and ASP.NET have a vulnerability where if you send a ff1c and ff1e symbols, which are full width greater and less than, then they can get automatically translated to greater than symbols when inserted into the database.  so when they come out, they come out as < and >.  They don't get blocked by the default XSS protection in .net so a surprising amount of .net sites are vulnerable to this.

**Comment by s0md3v** [comment]
I will confirm and implement it into XSStrike asap.
Thanks.

**Comment by s0md3v** [comment]
Hi @digitalpacman ,

I just confirmed that it works.
Now I would like to have your opinion on how this should be implemented.
I can think of 3 solutions:
1. Introduce a sqlmap like `--tamper` option, `ascii2unicode` being a bypass script. We can have other bypasses added this way.
2. Check if `%EF%BC%9C` is being translated to `<` everytime. It will cost us 1 extra request everytime.
3. Use `wappalyzer` API (without token :wink: ) to detect if the target website uses `ASP.NET`. It will cost us another request too but we can use this technology detection in future for application specific bypasses.

**Comment by s0md3v** [comment]
Hi @digitalpacman ,

The characters do get converted to full width angular brackets but they don't seem to work on `Firefox 62.0.3`.
The browser doesn't treat those characters as regular angular brackets.
The blog post that you mentioned dates back to 22 March, 2016 and it is possible that it got patched on the browser level.

Screenshot:
![screenshot_2018-11-15_18-14-30](https://user-images.githubusercontent.com/26716802/48556242-71525a00-e909-11e8-9bcc-c6467627524f.png)

**Comment by digitalpacman** [comment]
The problem is they get stored as normal angle brackets in SQL server. I
haven't tested SQL server 2018.

I don't have a running instance of SQL server to test on.  I'll maybe look
into it.  But basically you have a utf8 encoded website.  Language doesnt
matter.  Allow an insertion into db with large angles.  You will likely
have to use fiddler, not a browser input field.  You likely also I believe
have to specify the he encoded form.  But then it'll decode on the back end
and SQL will convert it.  Then when it's read, it's a normal HTML bracket

**Comment by digitalpacman** [comment]
I'm making a reply again because "Browser level" doesn't matter. This is still a vulnerability on lots of asp.net sites (one I worked at as well, and is still vulnerable to stored XSS).

I verified this behavior still exists in SQL Server 2018.  It's simply how they handle encoding that character.

So if you make a forced scripted submission to a website, using a custom script and not a browser, and input the wide <> they will bypass security checks and get turned into normal sized <>.  Then if they are not html encoded on the output, there will be stored XSS.

Lots of asp.net developers will often rely on the default safety of the XSS validator to prevent the request.  So they get lazy and don't html encode their outputs because they incorrectly believe all input is safe.

**Comment by s0md3v** [comment]
Hi @digitalpacman ,

Would it be possible for you to share the webpage you verified this behaviour on? In private?
You can mail me at s0md3v@gmail.com or dm at [twitter](https://twitter.com/s0md3v)

I am still confused about how  it works.
Does it work only when the input gets stored in the database?

**Comment by digitalpacman** [comment]
I'll try setting up an amazon instance I guess.

Yes it only works when it's inputted into the database. SQL Server literally changes wide < to short < during inserts.  So if you do insert into table values (0xff1e) then you when you do select column you get back the text "<", NOT the wide angle bracket.  And the default asp.net XSS checker does NOT check for wide <.
