### ISSUE TITLE
On GPLv3

### ISSUE THREAD

**Issue by jhabdas** [s0md3v/XSStrike#103]
> If you don't follow the conditions, you might get into trouble.

Using this license will pretty much ensure conditions aren't followed. In fact, the GPL is the reason  WTFPL exists. Have you looked at Zlib license? If you're interested in this software being improved upon by others you may have better luck switching. If that's not your aim you could probably remove the license altogether.

**Comment by s0md3v** [comment]
I want others to collaborate but the only thing I am worried about is unethical copying of the code, that's why I used GPL and used that particular statement.

**Comment by jhabdas** [comment]
Thanks for the rationale. Apache is fairly approachable too. I've seen people goof up MIT so something easier might be more digestible and less of a hinderance for the adoption of business customers.

**Comment by s0md3v** [comment]
@jhabdas I don't really want it to be used as a part of a closed source commercial tool because I am giving it to the community for free, not to business.
That's why I am offering an propriety license because I personally don't think it's nice if you spend a month writing a software and someone else makes money with it.

**Comment by jhabdas** [comment]
> I personally don't think it's nice if you spend a month writing a software and someone else makes money with it.

In my experience people tend to make money based on skill, not what's in their toolbox. IMHO digital tools are a dime a dozen. That's not too say what you've built here isn't novel and fantastic. What I'm suggesting is that GPL is probably the hardest license out there in terms of understanding and, therefore, can lead to unintended abuse.

If the idea is to limit businesses from making money on your stuff WTFPL is it. Otherwise please consider taking a look at Apache and Zlib licenses in your future work. Cheers.

**Comment by Serkan-devel** [comment]
Why not consider AGPL?

**Comment by jhabdas** [comment]
AGPL is a flavor of GPL. You can see how it plays in to the rest of 'em by looking at the [compatibility matrix](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) on the GPU website – a prime example of what I was trying to describe earlier regarding misuse.
