### ISSUE TITLE
Can't open the xsstrike by python3 

### ISSUE THREAD

**Issue by hieutrandn9889** [s0md3v/XSStrike#114]
Hello,

I can't run xsstrike by python3 :
That is my log:
"python3 xsstrike.py -u "https://public-firing-range.appspot.com/reflected/index.html" --crawl
	XSStrike v3.0.2
Traceback (most recent call last):
  File "xsstrike.py", line 34, in <module>
    from core.checker import checker
  File "/root/Desktop/hack web/XSStrike/core/checker.py", line 3, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'

Plz help me to reslove this issue

**Comment by s0md3v** [comment]
I think you should take a look at the documentation first.
Anyway, you have to install `fuzzywuzzy` with the following command

`pip3 install fuzzywuzzy`
