### ISSUE TITLE
when im using -f default im getting this error

### ISSUE THREAD

**Issue by V33RU** [s0md3v/XSStrike#119]
Traceback (most recent call last):
  File "xsstrike.py", line 295, in <module>
    bruteforcer(target, paramData, payloadList, verbose, encoding)
  File "xsstrike.py", line 281, in bruteforcer
    for paramName in params.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by s0md3v** [comment]
Are you sure you supplied parameters?

Wrong
`python xsstrike.py -u http://example.com`

Right
`python xsstrike.py -u http://example.com/search.php?q=query`
or
`python xsstrike.py -u http://example.com --data {'q':'query'}`

If you want to target a whole website, you should use the crawling mode.

**Comment by V33RU** [comment]
thanks
