### ISSUE TITLE
Some features dont work -  continue scanning? [y/N] y

### ISSUE THREAD

**Issue by Kamerabuilt** [s0md3v/XSStrike#131]
Hi, 

I am using XSStrike v3.0.3, and the following feature does not work: 

 [?] Would you like to continue scanning? [y/N] y
bash: y: command not found
[9]+  Stopped

**Comment by Kamerabuilt** [comment]
Screenshot: 

![xss](https://user-images.githubusercontent.com/1248213/48640139-b6c36580-e9a3-11e8-9741-92cf07387f34.PNG)

**Comment by coIev** [comment]
try running with ./xsstrike.py -u http://brutelogic.com.br/xss.php --data "b1=123&b2=133&b3=hello"

include the " with data

**Comment by s0md3v** [comment]
Whenever there's a "&" in your URL or data, please enclose it with double quotes to make sure the terminal doesn't treat it as a special character.

Wrong
`python xsstrike.py -u http://example.com/search.php?q=query&action=submit`

Right
`python xsstrike.py -u "http://example.com/search.php?q=query&action=submit"`

**Comment by Kamerabuilt** [comment]
that did it, thanks. 
Suggestion: can we include something about it in the help menu?

**Comment by s0md3v** [comment]
Well this is something all linux users should know and doesn't really come under the scope of XSStrike's documentation but I will add it anyway.

**Comment by Kamerabuilt** [comment]
True, most --data has to include "POST DATA"
