### ISSUE TITLE
Some Features do not work - Payload

### ISSUE THREAD

**Issue by Kamerabuilt** [s0md3v/XSStrike#132]
Hi,

I am using XSStrike v3.0.3, and the following feature does not work:

When a payload is found, it is not displayed in one line, but as follow: 

```
Payload
<detAilS
onPOiNTErENtER
=
confirm() x//
[!] Efficiency: 100
[!] Confidence: 10
```

**Comment by coIev** [comment]
Could you give more steps to reproduce? Payload generation is fine for me.

![download](https://user-images.githubusercontent.com/44411392/48639586-d600c980-e988-11e8-9fff-0c85f4fc320f.png)

Also, try cloning the latest (v3.0.4) and check if that fixes.

**Comment by Kamerabuilt** [comment]
Here is a screenshot: 

![xss2](https://user-images.githubusercontent.com/1248213/48640238-1457b200-e9a4-11e8-9bfd-a10b034d1824.PNG)

**Comment by Kamerabuilt** [comment]
![xss3](https://user-images.githubusercontent.com/1248213/48640292-40733300-e9a4-11e8-985d-b7e74904d9f7.PNG)

**Comment by coIev** [comment]
This also happens on v3.0.4 @s0md3v 

http://prntscr.com/lj9udu

**Comment by s0md3v** [comment]
I am unable to reproduce this
![screenshot_2018-11-17_00-30-08](https://user-images.githubusercontent.com/26716802/48641495-fa4bbd00-e9ff-11e8-8cfb-2d72b6423a1e.png)

Please re-clone and try again.

**Comment by coIev** [comment]
No idea what's going on here. Payloads such as ("><DETAIls/+/ONTOGgLe+=+(confirm)() and ("><a/+/OnpoIntErenter+=+confirm() show up fine with others have some weird space. I re-cloned and ran it again and got the same issue.

http://prntscr.com/lja19v/direct

**Comment by s0md3v** [comment]
@coIev Can you show me the exact command that you ran?
Looks like the URL encoded characters are getting decoded automatically somehow.
I am unable to reproduce this on my machine.

**Comment by coIev** [comment]
> @coIev Can you show me the exact command that you ran?
> Looks like the URL encoded characters are getting decoded automatically somehow.
> I am unable to reproduce this on my machine.

python3 xsstrike.py -u http://brutelogic.com.br/xss.php --data "b1=123&b2=133&b3=hello" --skip

**Comment by s0md3v** [comment]
I got it, it only happens when use POST method.
I will fix it in a minute.

**Comment by Kamerabuilt** [comment]
another screenshot: 

![xss4](https://user-images.githubusercontent.com/1248213/48641901-40296680-e9a9-11e8-96ad-80b7ed08e44f.PNG)

My understanding is that we should be able to copy/paste the Payload and confirm the XSS manually, is that correct?

**Comment by s0md3v** [comment]
Welcome to XSStrike.
Bug fixes don't take more than hour here once the developer sees it ;)

**Comment by Kamerabuilt** [comment]
Looks good so far, I will run more tests tomorrow. Thank you for the quick response

**Comment by gauravlinux** [comment]
if ( /world101\.cfr\.org/.test(window.location.href) ) {
------------------------------------------------------------
[-] WAF detected: CloudFlare Web Application Firewall (CloudFlare) 
[!] Testing parameter: keywords 
[!] Reflections found: 2 
[~] Analysing reflections 
[~] Generating payloads 
[!] Payloads generated: 5 
 ~] Progress: 5/5
what is the payload it used ??????
