### ISSUE TITLE
Have a way to specify a csv file of urls or a text file

### ISSUE THREAD

**Issue by sniff122** [s0md3v/XSStrike#135]
**Is your feature request related to a problem? Please describe.**

I hate needing to manually put a url parameter, the utility itself is great but it would be nice to specify a CSV file or text file of URLs to test

**Describe the solution you'd like**
have a --urlfile parameter to specify a file with URLs stored to use instead of the -u parameter
**Additional context**
python3 xsstrike.py --urlfile URLs.csv --crawl --blind

**Comment by s0md3v** [comment]
Now you can supply a file containing URLs to crawl/test with `--seeds` option.
More information on the same can be found [here](https://github.com/s0md3v/XSStrike/wiki/Usage#testingcrawling-urls-from-a-file).

**Comment by sniff122** [comment]
For the --seed argument, can you specify a CSV file with each URL on a new line?

**Comment by s0md3v** [comment]
Yes, you can supply any file as long as it has URLs seperated by new line.

**Comment by sniff122** [comment]
Amazing
