### ISSUE TITLE
"Most" advanced XSS detection suite. 

### ISSUE THREAD

**Issue by jakelacey2012** [s0md3v/XSStrike#140]
Saying that makes me think that you have the stats to back it up. [You don't.](https://github.com/s0md3v/XSStrike/wiki/FAQ#why-xsstrike-boasts-that-it-is-the-most-advanced-xss-detection-suite) 

This is clearly clickbait.

**Comment by s0md3v** [comment]
Show me something better and I will definitely remove it :)
Also, this is an open source software and I don't make money from it in any way so I don't think I have a reason to make it a clickbait.

**Comment by s0md3v** [comment]
@jakelacey2012 By the way, thanks for asking if I have stats to back it up.
I guess I can run some tests and create a comparison table and I hope that won't be disrespectful to the other developers.

**Comment by jakelacey2012** [comment]
> Show me something better and I will definitely remove it :)
I think you're missing the point I'm trying to make, I'm not saying find something better. What I'm saying is you can list other XSS tool suites and provide arguments why this is better, Which would be a totally valid thing to do. :) 

> Also, this is an open source software and I don't make money from it in any way so I don't think I have a reason to make it a clickbait.

So you do benefit, which you're totally allowed to do by the way!! Maybe not directly but definitely indirectly.

Also you don't have to listen to me :) if you're fine leaving it as is then thats okay. Close this issue.

**Comment by s0md3v** [comment]
I respect your question but I don't want to have a comparison table within the project.
I think that will be disrespecting to other developers, I will remove the "most advanced" title instead.
Thanks for the issue, I will remove the title in next commit.

**Comment by TimurNurlygayanov** [comment]
The most one should find all XSS issues in game https://xss-game.appspot.com

It's like a Turing test for XSS scaner :)

**Comment by s0md3v** [comment]
Your question got answered [here](https://github.com/s0md3v/XSStrike/wiki/Comparing-XSStrike-with-other-XSS-Scanners) :)
