### ISSUE TITLE
Can't parse URLs without '?'

### ISSUE THREAD

**Issue by TimurNurlygayanov** [s0md3v/XSStrike#144]
**Describe the bug**
Scanner can't crawl web pages without symbol '?'

**To Reproduce**
Run something like:
python3 xsstrike.py -u "https://google.com/test/test2"

**Observed Result:**
```
 Checking for DOM vulnerabilities
Traceback (most recent call last):
  File "xsstrike.py", line 130, in <module>
    scan(target, paramData, verbose, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/Users/t.nurlygaianov/XSStrike/modes/scan.py", line 40, in scan
    params = getParams(target, paramData, GET)
  File "/Users/t.nurlygaianov/XSStrike/core/utils.py", line 148, in getParams
    data = url.split('?')[1]
IndexError: list index out of range

```
**Potential cause or fix**
Need at least check that '?' is presented in URL and also try XSS injection for pages without parameters.

**Environment:**
 - OS: MacOS
 - Python version: 3.7.1

**Comment by s0md3v** [comment]
You have to use the `--crawl` option for crawling.
