### ISSUE TITLE
log to file

### ISSUE THREAD

**Issue by sniff122** [s0md3v/XSStrike#146]
**Is your feature request related to a problem? Please describe.**
not related to a problem
**Describe the solution you'd like**
have a --log or similar command to log the output and possibly have an option to change the log level from the same output to just if there was a vulnerability found
**Additional context**
python3 xsstrike.py --log vulnerable log.log ...
python3 xsstrike.py --log all log.log ...
python3 xsstrike.py --log notvulnerable log.log ...

**Comment by TheCrott** [comment]
+1 this
also, add an option to export payloads only

**Comment by nemoload** [comment]
There are many print statements scattered in the code, so instead of duplicating every string in those functions I thought maybe creating a unified printing and logging function would be better in terms of less redundancy.
```python
# Instead of:
log('%s Testing parameter: %s' % (info, paramName))
print('%s Testing parameter: %s' % (info, paramName))

#We can write something like:
logprint('%s Testing parameter: %s' % (info, paramName))
```
What do you think?

**Comment by s0md3v** [comment]
Sounds good. Are you going to use a flag for everything that needs to be printed only when user has enabled verbose logging?

```python
logprint('%s Logging this!' % info, log=True)
```

**Comment by nemoload** [comment]
I'll use a flag of course but I prefer to make it internal.

**Comment by s0md3v** [comment]
well, I believe in you. Do it your way, I'll merge it.

**Comment by sniff122** [comment]
Is there an update on the state of this feature request?

**Comment by s0md3v** [comment]
@nemoload aren't you working on it? If not, I will do it.

**Comment by nemoload** [comment]
I'm having my exams right now. I'll probably go back to work on it when I get done with it. On Jan 2, 2019 11:33 PM, Somdev Sangwan <notifications@github.com> wrote:@nemoload aren't you working on it? If not, I will do it.

**Comment by s0md3v** [comment]
Alright, I started working on it. Good luck for your exams :heart: 

### Implementation
```
logger(data, flag=None, variable=None, function=None)
```
This function which is defined in `utils.py` handles normal printing, debug output, verbose output as well as logging to file needs.

#### Arguments

- `data`: data to be logged
- `flag`: a flag describing how to treat this data
    - `debug` debugging
    - `log` logging to file
   - `verbose` verbose output
- `variable` variable that contains the data (for debugging mode only)
- `function` function that contains the variable (for debugging mode only)

#### Progress
I just need to implement log to file thingy, everything else is done.

**Comment by s0md3v** [comment]
@pyneda implemented this and the documentation of the logging mechanism can be found [here](https://github.com/s0md3v/XSStrike/wiki/Usage#logging).

**Comment by sniff122** [comment]
Nice, amazing! Can't wait to get using it again

**Comment by sniff122** [comment]
@s0md3v I have updated XSStrike and i do not have the logging function
![image](https://user-images.githubusercontent.com/8513053/51445314-8b3e5d80-1cfb-11e9-8bed-4a7bd15ad2cd.png)
