### ISSUE TITLE
XsStrike not find any xss on https://www.root-me.org

### ISSUE THREAD

**Issue by thelittlefireman** [s0md3v/XSStrike#149]
**Describe the bug**
https://www.root-me.org is a simple web site with Several web environment allow users to test their skills legally.

**To Reproduce**
Use Xsstrike on thoses challenges : 
https://www.root-me.org/fr/Challenges/Web-Client/XSS-Stored-1
https://www.root-me.org/fr/Challenges/Web-Client/XSS-Stockee-2

but it didn't find any xss vulnerabilities. Thoses tow challenge are very simple. Could it be possible to improve xsstrike ?

**Screenshots**
If applicable, add screenshots or paste terminal output to help explain your problem.
Feel free to hide sensitive information like the URL of the target.

**Potential cause or fix**
Do you know what could be causing the problem or how to fix it?

**Environment:**
 - OS: Kali 2018.2
 - Browser Firefox 63 and chrome
 - Python version 3.7

**Some Questions**

- [ ] I am using the latest version of XSStrike.
- [ ] I installed the dependecies using `pip3` instead of `pip`
- [ ] I have read the documentation before submitting this issue.
- [ ] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?

**Comment by s0md3v** [comment]
Since stored input can reflect on any page, XSStrike has no straight forward way to check for stored XSS.
However, you can use `--crawl`  and `--blind` options to together to achieve the same.

Also, if the target is behind authentication, make sure you supply the headers required to access the resource.
