### ISSUE TITLE
Json Injection

### ISSUE THREAD

**Issue by Fadavvi** [s0md3v/XSStrike#151]
Hi,

First of all thanks for your application, then I tried to XSS in a JSON POST data but XSStrike show this error:

No parameters to test.

xsstrike.py -u 'http://xyz.abc//temp.php?parvaz=141' --data '{"Code": "1"}' --fuzzer

I don't know! this is a bug or you didn't support JSON data!

Python 3.6.3 / Win 10 & Fedora 7 workstation tested !

Best regards,
Milad

**Comment by s0md3v** [comment]
Hi @Fadavvi ,

A new switch `--json` has been introduced to allow injection within JSON data.
Can you please confirm that it works?

Usage

`python3 xsstrike.py -u https://example.com/form.php --data='{"q":"query"}' --json`

**Comment by Fadavvi** [comment]
JSON:  '{"CodeRahgiriTemp": "1"}'
Run: python3 .\xsstrike.py -u 'http://1.com/temp.php' --data='{"CodeRahgiriTemp": "1"}'  --json

Last Error:  
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Full traceback: 

Traceback (most recent call last):
  File ".\xsstrike.py", line 113, in <module>
    paramData = converter(paramData)
  File "C:\Users\ANPSec\Desktop\XSStrike-master\core\utils.py", line 19, in converter
    return json.loads(data)
  File "C:\Users\ANPSec\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ANPSec\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ANPSec\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by s0md3v** [comment]
Works fine for me. Are you sure you re-cloned the repository?
![screenshot_2018-11-26_19-34-50](https://user-images.githubusercontent.com/26716802/49018875-8a34f800-f1b2-11e8-9f5a-8fcdfd272d94.png)

**Comment by Fadavvi** [comment]
I'll check. Thanks for your quick response.
