### ISSUE TITLE
	XSStrike v3.1.1  [-] XSStrike isn't compatible with python2.  Use python > 3.4 to run XSStrike.

### ISSUE THREAD

**Issue by Aravindd007** [s0md3v/XSStrike#158]
**Describe the bug**

**To Reproduce**
Explain how the issue can be reproduced.

**Screenshots**
If applicable, add screenshots or paste terminal output to help explain your problem.
Feel free to hide sensitive information like the URL of the target.

**Potential cause or fix**
Do you know what could be causing the problem or how to fix it?

**Environment:**
 - OS: [e.g. Kali Rolling 2018.2]
 - Browser [e.g. Firefox 60.2]
 - Python version [e.g. 3.7]

**Some Questions**

- [x] I am using the latest version of XSStrike.
- [ ] I installed the dependecies using `pip3` instead of `pip`
- [ ] I have read the documentation before submitting this issue.
- [ ] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?

**Comment by Aravindd007** [comment]
XSStrike v3.1.1

[-] XSStrike isn't compatible with python2.
 Use python > 3.4 to run XSStrike.
how can i fix?

**Comment by Aravindd007** [comment]
i am so sorry pip problem

**Comment by s0md3v** [comment]
Run it with python 3 as follows:
```
python3 xsstrike.py -u http://example.com/search.php?q=query
```

**Comment by Aravindd007** [comment]
Traceback (most recent call last):
  File "xsstrike.py", line 26, in <module>
    from core.photon import photon
  File "/root/Desktop/XSStrike/core/photon.py", line 7, in <module>
    from core.requester import requester
  File "/root/Desktop/XSStrike/core/requester.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Aravindd007** [comment]
python3 xsstrike.py -u http://example.com/search.php?q=query
it's not working

**Comment by s0md3v** [comment]
You should learn how to troubleshoot errors yourself :)
Use google before asking other people.

**Comment by Aravindd007** [comment]
ok thanks man

**Comment by Hariprasanth03SN** [comment]
Traceback (most recent call last):
  File "xsstrike.py", line 26, in <module>
    from core.photon import photon
  File "/root/Desktop/Tools/XSStrike/core/photon.py", line 7, in <module>
    from core.requester import requester
  File "/root/Desktop/Tools/XSStrike/core/requester.py", line 2, in <module>
    import requests
ImportError: No module named 'requests'

any solution for this

**Comment by Aravindd007** [comment]
try version XSStrike-1-master it's work well

**Comment by Aravindd007** [comment]
> Traceback (most recent call last):
> File "xsstrike.py", line 26, in
> from core.photon import photon
> File "/root/Desktop/Tools/XSStrike/core/photon.py", line 7, in
> from core.requester import requester
> File "/root/Desktop/Tools/XSStrike/core/requester.py", line 2, in
> import requests
> ImportError: No module named 'requests'
> 
> any solution for this
try version XSStrike-1-master it's work well

**Comment by Aravindd007** [comment]
hey i got the solution for this
1. pip install pygame
2. pip3 install pygame
3. open xsstrike and run : pip3 install -r requirements.txt
4. python3 xsstrike.py
now it's working thanks:)

**Comment by Hariprasanth03SN** [comment]
Traceback (most recent call last):
  File "xsstrike.py", line 26, in <module>
    from core.photon import photon
  File "/root/Desktop/Tools/XSStrike/core/photon.py", line 7, in <module>
    from core.requester import requester
  File "/root/Desktop/Tools/XSStrike/core/requester.py", line 2, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by s0md3v** [comment]
Install `requests` library with pip3.
Try to read the fucking documentation before coming up with an issue, I am not your customer support.

**Comment by zhuyingda** [comment]
If someone has tried

> Install `requests` library with pip3

but still got this issue, try to reinstalling pip3 on your system.

This could be helpful for you.

**Comment by Eat-Sleep-Code-fun** [comment]
@Aravindd007 Run below commands, to solve your ```photon.py``` and ```requester.py``` error.

1. curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
2. python3 get-pip.py --force-reinstall
3. sudo pip3 install tld
4. pip3 install requester

Thanks
