### ISSUE TITLE
Feature Improvement : Display XSS Payload Reflecting Parameters

### ISSUE THREAD

**Issue by ericnyamu1** [s0md3v/XSStrike#159]
Hey,

Xsstrike is very nice and easy to use but it would be nice if after it has scanned for xss vulnerabilities and has found none it can output which parameters are reflecting the xss paylaod but it (xsstrike) isnot able to pop an alert box.That way the tester can try out other different xss payloads that might work.

Thanks

**Comment by s0md3v** [comment]
Oh well XSStrike already lets you know if a parameter is reflecting the input e.g.
```
[!] Testing parameter: q
[!] Reflections found: 8
```
