### ISSUE TITLE
Error when scan github.com

### ISSUE THREAD

**Issue by GetRektBoy724** [s0md3v/XSStrike#161]
**Describe the bug**

**To Reproduce**
Explain how the issue can be reproduced.

**Screenshots**
If applicable, add screenshots or paste terminal output to help explain your problem.
Feel free to hide sensitive information like the URL of the target.

**Potential cause or fix**
Do you know what could be causing the problem or how to fix it?

**Environment:**
 - OS: [e.g. Kali Rolling 2018.2]
 - Browser [e.g. Firefox 60.2]
 - Python version [e.g. 3.7]

**Some Questions**

- [ ] I am using the latest version of XSStrike.
- [ ] I installed the dependecies using `pip3` instead of `pip`
- [ ] I have read the documentation before submitting this issue.
- [ ] I have checked the other issues to see if someone reported this before.

**Other comments**

┌─[root@parrot-armhf]─[/home/parrot/XSStrike]
└──╼ #python3 xsstrike.py -u https://github.com

XSStrike v3.1.1

Traceback (most recent call last):
  File "xsstrike.py", line 32, in <module>
    from modes.crawl import crawl
  File "/home/parrot/XSStrike/modes/crawl.py", line 7, in <module>
    from core.filterChecker import filterChecker
  File "/home/parrot/XSStrike/core/filterChecker.py", line 1, in <module>
    from core.checker import checker
  File "/home/parrot/XSStrike/core/checker.py", line 2, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'

**Comment by s0md3v** [comment]
Read the documentation

**Comment by radenvodka** [comment]
pip install fuzzywuzzy
