### ISSUE TITLE
Maybe error in fuzzer.py

### ISSUE THREAD

**Issue by Maskhe** [s0md3v/XSStrike#163]
![image](https://user-images.githubusercontent.com/30264078/49216057-1b031200-f405-11e8-8fd0-31487561fd99.png)
if the execution sequence likes what I described on the image ,will I get an error?? I didn`t put it into practice ,I just view and  learn your code (By the way ,I`m Chinese ,so my english isn`t so good,hope you can get what I said)

**Comment by s0md3v** [comment]
Run it!
