### ISSUE TITLE
TypeError: sub() missing 1 required positional argument: 'string'

### ISSUE THREAD

**Issue by blackwolfsec** [s0md3v/XSStrike#167]
**Describe the bug**
	XSStrike v3.1.1

[+] WAF Status: Offline
[!] Fuzzing parameter: name
Traceback (most recent call last):
  File "xsstrike.py", line 139, in <module>
    singleFuzz(target, paramData, verbose, encoding, headers, delay, timeout)
  File "/tmp/XSStrike/modes/singleFuzz.py", line 42, in singleFuzz
    delay, timeout, WAF, encoding)
  File "/tmp/XSStrike/core/fuzzer.py", line 16, in fuzzer
    t = delay + randint(delay, delay * 2) + counter(fuzz)
  File "/tmp/XSStrike/core/utils.py", line 31, in counter
    string = re.sub(r'\s|\w', '')
TypeError: sub() missing 1 required positional argument: 'string'

**To Reproduce**
git clone the latest code
pip3 install -r requirements.txt
python3 xsstrike.py -u "http://127.0.0.1/1.php?name=123" --fuzzer

**Potential cause or fix**
how to fix it?

> diff --git a/core/utils.py b/core/utils.py
index 7683406..7e6e529 100644
--- a/core/utils.py
+++ b/core/utils.py
@@ -28,7 +28,7 @@ def converter(data, url=False):
 def counter(string):
\-    string = re.sub(r'\s|\w', '')
\+    string = re.sub(r'\s|\w', '',string)
     return len(string)

**Environment:**
 - ubuntu 16.04
 - Python 3.5.2

**Comment by anilbkt** [comment]
re.sub(r'\s|\w', '') -> This is missing the source string.
E.g. re.sub(r'\s|\w', '', str)
