### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by rajvardhan7744** [s0md3v/XSStrike#173]
root@kali2018:~/Desktop/XSStrike# ./xsstrike.py 

	XSStrike v3.1.1

Traceback (most recent call last):
  File "./xsstrike.py", line 32, in <module>
    from modes.crawl import crawl
  File "/root/Desktop/XSStrike/modes/crawl.py", line 7, in <module>
    from core.filterChecker import filterChecker
  File "/root/Desktop/XSStrike/core/filterChecker.py", line 1, in <module>
    from core.checker import checker
  File "/root/Desktop/XSStrike/core/checker.py", line 2, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'

**Comment by rajvardhan7744** [comment]
root@kali2017:~/Desktop/XSStrike# pip install -r requirements.txt
Collecting tld (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a3/31/bbea249ca4c6117663e91dfa5a42137badb9d304c306f054a82c12e4941b/tld-0.9.1-py2.py3-none-any.whl (225kB)
    100% |████████████████████████████████| 225kB 519kB/s 
Collecting fuzzywuzzy (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/d8/f1/5a267addb30ab7eaa1beab2b9323073815da4551076554ecc890a3595ec9/fuzzywuzzy-0.17.0-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Collecting selenium (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904kB)
    100% |████████████████████████████████| 911kB 416kB/s 
Requirement already satisfied: six>=1.9 in /usr/local/lib/python2.7/dist-packages (from tld->-r requirements.txt (line 1))
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from selenium->-r requirements.txt (line 4))
Installing collected packages: tld, fuzzywuzzy, selenium
Successfully installed fuzzywuzzy-0.17.0 selenium-3.141.0 tld-0.9.1
root@kali2017:~/Desktop/XSStrike# ./xsstrike.py 

	XSStrike v3.1.1

Traceback (most recent call last):
  File "./xsstrike.py", line 32, in <module>
    from modes.crawl import crawl
  File "/root/Desktop/XSStrike/modes/crawl.py", line 7, in <module>
    from core.filterChecker import filterChecker
  File "/root/Desktop/XSStrike/core/filterChecker.py", line 1, in <module>
    from core.checker import checker
  File "/root/Desktop/XSStrike/core/checker.py", line 2, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'

**Comment by s0md3v** [comment]
Read the documentation.
