### ISSUE TITLE
No params how to fuzz?

### ISSUE THREAD

**Issue by djerrystyle** [s0md3v/XSStrike#175]
url like this **xxx.com/Goods/proRdy/id/433;"XSS_here**

this is normal url in thinphp framework , but how to start fuzz 

when put this url , and get :
```
XSStrike v3.1.1
[-] No parameters to test.
```

Also, i try to build url like :  **xxx.com/Goods/proRdy/id/433;"?p=XSS_here**
but it will redirect to index page , so can i provide a special word in where i wanna fuzz

**Comment by s0md3v** [comment]
Use --path switch, refer to documention for a detailed usage guide.
