### ISSUE TITLE
Redirection Feature

### ISSUE THREAD

**Issue by az0mb13** [s0md3v/XSStrike#191]
I have come across many websites which inject xss at one page and display reflection at other, My request is how about you add another url parameter where the reflection is possible and make it optional for users to add?
Because sometimes, due to multiple reasons websites won't let you redirect properly or won't redirect at all if you're not carrying out that request from within a browser.
If they're sure the url where reflection is happening they'll just add this extra url in the arguments.

**Comment by shadowzoom** [comment]
@aditya007o yeah i need that too :c Did you resolve somehow this? Or maybe you can suggest fork?

**Comment by shadowzoom** [comment]
@s0md3v  hey mate, 2 month have been passed :c When you will be have the free time to finish this feature?
