### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by shadowzoom** [s0md3v/XSStrike#203]
I have command - python3 xsstrike.py -u "https://example.com/rrr" --path i'm getting:

------------------------------------------------------------
[+] WAF Status: Offline
[!] Testing parameter: test
[!] Reflections found: 3
[~] Analysing reflections
[~] Generating payloads
[!] Payloads generated: 5
Traceback (most recent call last):
  File "xsstrike.py", line 167, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "C:\Users\Admin\Desktop\Tools\XSStrike\modes\scan.py", line 135, in scan
    success = browserEngine(response)
  File "C:\Users\Admin\Desktop\Tools\XSStrike\core\browserEngine.py", line 13, in browserEngine
    browser = webdriver.Firefox(options=options)
TypeError: __init__() got an unexpected keyword argument 'options'

Any tips how to fix?

**Comment by s0md3v** [comment]
Are you sure you have `selenium`, `geckodriver` and Firefox browser installed?
