### ISSUE TITLE
Check xss on second page

### ISSUE THREAD

**Issue by shadowzoom** [s0md3v/XSStrike#206]
In example all data submiting on 1st page via post
site.com/useredit.php
{name=test}
And then user data appearing on second page site.com/user.php?id=1
Is there a method to check second page for xss when data was sended to the first page?

**Comment by s0md3v** [comment]
No, but it will be added in future.
Closing this as a duplicate of  #191

**Comment by shadowzoom** [comment]
Hi Miroslav @stamparm, it would be great if you can join to developers of https://github.com/s0md3v/XSStrike
It use some code of sqlmap and will be great if xsstrike will be develop amazing pro coder like you

**Comment by shadowzoom** [comment]
@s0md3v great! Thanks! How long we need to wait, do you have approximate dates?

**Comment by shadowzoom** [comment]
@s0md3v  any update please? I can pay you $10 bucks for it mate :c

**Comment by shadowzoom** [comment]
@s0md3v  hey mate, 2 month have been passed :c When you will be have the free time to finish this feature?

**Comment by s0md3v** [comment]
Sorry mate, I have been dealing with depression and shit. I will get to it soon.

**Comment by shadowzoom** [comment]
@s0md3v  hi again! :) Any updates about this feature? How are you btw?
