### ISSUE TITLE
strange proplem 

### ISSUE THREAD

**Issue by mwamiaim** [s0md3v/XSStrike#210]
i watch perceives issue but i don't find issue that happened to me , i install requirements.txt and requests with pip3 , and i do chmod +x xsstrike.py , but when i type python3 xsstrike.py i got this : 
root@kali:~/XSStrike# python3 xsstrike.py 

	XSStrike v3.1.2

Traceback (most recent call last):
  File "xsstrike.py", line 115, in <module>
    from core.photon import photon
  File "/root/XSStrike/core/photon.py", line 7, in <module>
    from core.requester import requester
  File "/root/XSStrike/core/requester.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by mrityunjay38** [comment]
Simply install requests from terminal

pip3 install requests
pip3 install tld
pip3 install selenium
pip3 install fuzzywuzzy
