### ISSUE TITLE
generate report with findings

### ISSUE THREAD

**Issue by javixeneize** [s0md3v/XSStrike#224]
Hi

I have scanned another application i have, which is vulnerable to XSS in purpose, and i have this report in the console:

	XSStrike v3.1.4

 Checking for DOM vulnerabilities
 WAF Status: Offline
 Testing parameter: user
 No reflection found
 Testing parameter: address
 Reflections found: 1
 Analysing reflections
 Generating payloads
 Payloads generated: 5
 Progress: 5/5

It just says that has found a reflection a has generated 5 payloads, but it does not say if the application is vulnerable to xss or not, or which payload (if any) has worked

Maybe it would be a good addition to generate a quick report with the findings?

Thanks

**Comment by s0md3v** [comment]
Hi there,

It generated 5 payloads but none of them worked and that's why no vulnerability was discovered.

Thanks for reporting.

**Comment by javixeneize** [comment]
Maybe it would help if it adds that no issues have been found :)
