### ISSUE TITLE
Handle reflection at the very end of a document

### ISSUE THREAD

**Issue by Conanjun** [s0md3v/XSStrike#226]
**Describe the bug**
[Redacted by s0md3v]

[Redacted by s0md3v]

maybe something wrong happen in the newest version.):

**Comment by Conanjun** [comment]
demo name wrong,it shuod bi web-for-pentester xss module

**Comment by s0md3v** [comment]
Hi @Conanjun ,

As the output suggests, the input isn't getting reflected in the webpage. Can you please confirm it manually?
As the name of the issue suggests, an earlier version of XSStrike worked well with this webpage. Can you please specify that version?

Thanks.

**Comment by Conanjun** [comment]
@s0md3v the demo is in https://pentesterlab.com/exercises/web_for_pentester/iso  , u could just download it and test xsstrike in 
![image](https://user-images.githubusercontent.com/7765655/55826500-be45ff80-5b3a-11e9-9e70-54121497b684.png)
it is a simple xss point but the xsstrike can not identified successfully. it is confusing :)
let me show u the demo code
![image](https://user-images.githubusercontent.com/7765655/55826633-08c77c00-5b3b-11e9-9edb-3db12dbabaf1.png)
and the scan result and the respon reflected
![image](https://user-images.githubusercontent.com/7765655/55826784-580dac80-5b3b-11e9-9a2a-26f0a75cbe8b.png)

some thing wong really happened,trust me plz :)

thanks

**Comment by Conanjun** [comment]
manual test result 
![image](https://user-images.githubusercontent.com/7765655/55827069-f6017700-5b3b-11e9-92ce-cfed9c100982.png)

**Comment by s0md3v** [comment]
Hi @Conanjun ,

I have confirmed this bug. It occurs when the input is reflected at the very end of the document.
A fix for this will be rolled out as soon as possible,

Thanks for reporting.

**Comment by Conanjun** [comment]
as u see, i have changed the demo while add some tag arround the reflected point to make it is not at the very end of document,but it still can not works,may be it was not the question that u haved answered. 
![image](https://user-images.githubusercontent.com/7765655/55849184-48fe1d00-5b82-11e9-9a8a-9c32d5347cbe.png)

**Comment by Conanjun** [comment]
@s0md3v

**Comment by s0md3v** [comment]
Yes @Conanjun ,

After further investigation, I found out the bug was not related to the reflection being a the end of the document.
However, I deployed a potential fix in the latest commit.
Can you verify if the issue still exists?

**Comment by Conanjun** [comment]
@s0md3v i have checked the fix,but it still can not work on for either the origin demo or the changed demo.:)

**Comment by s0md3v** [comment]
Well, it's working for me. Would you mind sharing the exact HTML (not PHP) source code?

**Comment by Conanjun** [comment]
here is the result and html
![image](https://user-images.githubusercontent.com/7765655/55855197-6c809200-5b99-11e9-9509-6011dbcf3de8.png)
`

  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>PentesterLab &raquo; Web for Pentester</title>
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <meta name="description" content="Web For Pentester">
  | <meta name="author" content="Louis Nyffenegger (louis@pentesterlab.com)">
  |  
  | 
  | <link href="/css/bootstrap.css" rel="stylesheet">
  |  
  | <style type="text/css">
  | body {
  | padding-top: 60px;
  | padding-bottom: 40px;
  | }
  | </style>
  | <link href="/css/bootstrap-responsive.css" rel="stylesheet">
  |  
  | </head>
  |  
  | <body>
  |  
  | <div class="navbar navbar-inverse navbar-fixed-top">
  | <div class="navbar-inner">
  | <div class="container">
  | <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | </a>
  | <a class="brand" href="https://pentesterlab.com/">PentesterLab.com</a>
  | <div class="nav-collapse collapse">
  | <ul class="nav">
  | <li class="active"><a href="/">Home</a></li>
  | </ul>
  | </div>
  | </div>
  | </div>
  | </div>
  |  
  | <div class="container">
  |  
  |  
  |  
  | <html>
  | hello
  | hacker      <footer>
  | <p>&copy; PentesterLab 2013</p>
  | </footer>
  |  
  | </div> 
  |  
  |  
  | </body>
  | </html>
  |  
  |  
  |  
  |  

`

**Comment by Conanjun** [comment]
**

  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>PentesterLab &raquo; Web for Pentester</title>
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <meta name="description" content="Web For Pentester">
  | <meta name="author" content="Louis Nyffenegger (louis@pentesterlab.com)">
  |  
  | 
  | <link href="/css/bootstrap.css" rel="stylesheet">
  |  
  | <style type="text/css">
  | body {
  | padding-top: 60px;
  | padding-bottom: 40px;
  | }
  | </style>
  | <link href="/css/bootstrap-responsive.css" rel="stylesheet">
  |  
  | </head>
  |  
  | <body>
  |  
  | <div class="navbar navbar-inverse navbar-fixed-top">
  | <div class="navbar-inner">
  | <div class="container">
  | <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | </a>
  | <a class="brand" href="https://pentesterlab.com/">PentesterLab.com</a>
  | <div class="nav-collapse collapse">
  | <ul class="nav">
  | <li class="active"><a href="/">Home</a></li>
  | </ul>
  | </div>
  | </div>
  | </div>
  | </div>
  |  
  | <div class="container">
  |  
  |  
  |  
  | <html>
  | hello
  | hacker      <footer>
  | <p>&copy; PentesterLab 2013</p>
  | </footer>
  |  
  | </div> 
  |  
  |  
  | </body>
  | </html>
  |  
  |  
  |  
  |  

**

**Comment by Conanjun** [comment]
| <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>PentesterLab &raquo; Web for Pentester</title>
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <meta name="description" content="Web For Pentester">
  | <meta name="author" content="Louis Nyffenegger (louis@pentesterlab.com)">
  |  
  | 
  | <link href="/css/bootstrap.css" rel="stylesheet">
  |  
  | <style type="text/css">
  | body {
  | padding-top: 60px;
  | padding-bottom: 40px;
  | }
  | </style>
  | <link href="/css/bootstrap-responsive.css" rel="stylesheet">
  |  
  | </head>
  |  
  | <body>
  |  
  | <div class="navbar navbar-inverse navbar-fixed-top">
  | <div class="navbar-inner">
  | <div class="container">
  | <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | </a>
  | <a class="brand" href="https://pentesterlab.com/">PentesterLab.com</a>
  | <div class="nav-collapse collapse">
  | <ul class="nav">
  | <li class="active"><a href="/">Home</a></li>
  | </ul>
  | </div>
  | </div>
  | </div>
  | </div>
  |  
  | <div class="container">
  |  
  |  
  |  
  | <html>
  | hello
  | hacker      <footer>
  | <p>&copy; PentesterLab 2013</p>
  | </footer>
  |  
  | </div> 
  |  
  |  
  | </body>
  | </html>
  |  
  |  
  |  
  |

**Comment by Conanjun** [comment]
@s0md3v the ghitub can not show the html code very well , let me share u with a file 
[xss-demo.txt](https://github.com/s0md3v/XSStrike/files/3062215/xss-demo.txt)

**Comment by Conanjun** [comment]
```html 
<a>aaaa</a>
```

**Comment by Conanjun** [comment]
```html

  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>PentesterLab &raquo; Web for Pentester</title>
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <meta name="description" content="Web For Pentester">
  | <meta name="author" content="Louis Nyffenegger (louis@pentesterlab.com)">
  |  
  | <!-- Le styles -->
  | <link href="/css/bootstrap.css" rel="stylesheet">
  |  
  | <style type="text/css">
  | body {
  | padding-top: 60px;
  | padding-bottom: 40px;
  | }
  | </style>
  | <link href="/css/bootstrap-responsive.css" rel="stylesheet">
  |  
  | </head>
  |  
  | <body>
  |  
  | <div class="navbar navbar-inverse navbar-fixed-top">
  | <div class="navbar-inner">
  | <div class="container">
  | <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | </a>
  | <a class="brand" href="https://pentesterlab.com/">PentesterLab.com</a>
  | <div class="nav-collapse collapse">
  | <ul class="nav">
  | <li class="active"><a href="/">Home</a></li>
  | </ul>
  | </div><!--/.nav-collapse -->
  | </div>
  | </div>
  | </div>
  |  
  | <div class="container">
  |  
  |  
  |  
  | <html>
  | hello
  | hacker      <footer>
  | <p>&copy; PentesterLab 2013</p>
  | </footer>
  |  
  | </div> <!-- /container -->
  |  
  |  
  | </body>
  | </html>
  |  
  |  
  |  
  |  



```

**Comment by s0md3v** [comment]
Thanks.
Next time put your code between \`\`\` and \`\`\` to make sure it's rendered as code
For example,
```
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8">
<title>PentesterLab &raquo; Web for Pentester</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Web For Pentester">
<meta name="author" content="Louis Nyffenegger (louis@pentesterlab.com)">
 
<!-- Le styles -->
<link href="/css/bootstrap.css" rel="stylesheet">
 
<style type="text/css">
body {
padding-top: 60px;
padding-bottom: 40px;
}
</style>
<link href="/css/bootstrap-responsive.css" rel="stylesheet">
 
</head>
 
<body>
 
<div class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
<a class="brand" href="https://pentesterlab.com/">PentesterLab.com</a>
<div class="nav-collapse collapse">
<ul class="nav">
<li class="active"><a href="/">Home</a></li>
</ul>
</div><!--/.nav-collapse -->
</div>
</div>
</div>
 
<div class="container">
 
 
 
<html>
hello
hacker      <footer>
<p>&copy; PentesterLab 2013</p>
</footer>
 
</div> <!-- /container -->
 
 
</body>
</html>
```

**Comment by s0md3v** [comment]
It has been fixed and I tested against the code you provided.
Let me know if you find any other false negatives.

**Comment by Conanjun** [comment]
@s0md3v your latest fix plan is quiet a litter the same to me ... ... ,but i don't think it is a right solution but let it go hah:) . may we talk personally after github?

**Comment by s0md3v** [comment]
@Conanjun The patch works because before this patch, the variables `tags` and `attributes` would stay empty causing the reflection to be not registered by XSStrike.

We can talk on twitter, hmu @s0md3v.
