### ISSUE TITLE
can't run xsstrike while installed fuzzywuzzy

### ISSUE THREAD

**Issue by hieutrandn9889** [s0md3v/XSStrike#232]
Hello all,

I want to run xsstrike but it doesn't work:

**That is my log:**
root@kali:~/Desktop/XSStrike# python3 xsstrike.py -u https://somdev.me/XSStrike/
 
	XSStrike v3.1.4

[!] fuzzywuzzy isn't installed, installing now.
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting fuzzywuzzy
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/fuzzywuzzy/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/fuzzywuzzy/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/fuzzywuzzy/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/fuzzywuzzy/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/fuzzywuzzy/
  Could not fetch URL https://pypi.org/simple/fuzzywuzzy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/fuzzywuzzy/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement fuzzywuzzy (from versions: )
No matching distribution found for fuzzywuzzy
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
[!] fuzzywuzzy has been installed, restart XSStrike.

**Note:**
 I installed fuzzywzzy 
Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python2.7/dist-packages (0.17.0)
python3-pip is already the newest version (18.1-5).
python --version: Python 2.7.16
python3 --version: Python 3.7.3

how to fix this issue ?

**Comment by s0md3v** [comment]
XSStrike only runs on Python 3
4 and above. Please install required modules using pip3 not pip.
