### ISSUE TITLE
ImportError: cannot import name 'Options'

### ISSUE THREAD

**Issue by vivianfrench2** [s0md3v/XSStrike#239]
Everytime I write this line, `python3 xsstrike.py -u https://www.care2.com` , I get an error.

`Traceback (most recent call last):
  File "xsstrike.py", line 124, in <module>
    from modes.scan import scan
  File "/root/XSStrike/modes/scan.py", line 6, in <module>
    from core.browserEngine import browser_engine, kill_browser, init_browser
  File "/root/XSStrike/core/browserEngine.py", line 8, in <module>
    from selenium.webdriver.firefox.options import Options
ImportError: cannot import name 'Options'`

**Comment by s0md3v** [comment]
Are you sure the `geckodriver` is set-up correctly and you have `firefox` and `selenium` installed?
If not, follow the commands below

```bash
wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
mkdir geckodriver
tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
export PATH=$PATH:$PWD/geckodriver
```
