### ISSUE TITLE
geckodriver problem!

### ISSUE THREAD

**Issue by Phoenix1112** [s0md3v/XSStrike#243]
hello... Firstly thank you for this beautiful project. .. i did install xsstrike .. but when i run it , i have geckodriver error..  i did download firefox geckodriver file.. I made the path settings... As shown in picture 1, the path settings are configured correctly.

![geckodriver](https://user-images.githubusercontent.com/42475284/58367168-ace76580-7ee4-11e9-94d6-16d71ba8245c.png)

If the path settings were configured incorrectly, this command would not work. (geckodriver -h)

I keep getting geckodriver error when I run xsstrike program.Do I need to set up a custom setting for the xsstrike program?

![xsstrike](https://user-images.githubusercontent.com/42475284/58367208-2e3ef800-7ee5-11e9-9f0a-dec4146149f8.png)

I would like to say that I am running xsstrike program on kali linux vps server.I couldn't see any setting for geckodriver on wiki page.

**Comment by s0md3v** [comment]
Try doing this
```bash
wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
mkdir geckodriver
tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
export PATH=$PATH:$PWD/geckodriver
```

**Comment by Phoenix1112** [comment]
problem not solved.. i think this is python3.7 problem..

**Comment by theNurky** [comment]
Same issue on Windows 10 (Python 3.7.4)

**Comment by s0md3v** [comment]
`selenium` has been removed, this issue isn't relevant anymore.
