### ISSUE TITLE
Modules Not Found

### ISSUE THREAD

**Issue by mrityunjay38** [s0md3v/XSStrike#244]
Hi
I am getting this error while running Xsstrike.py on my mac.

Traceback (most recent call last):
  File "xsstrike.py", line 117, in <module>
    from core.photon import photon
  File "/Users/mrityunjay/Desktop/XSS/XSS/core/photon.py", line 8, in <module>
    from core.requester import requester
  File "/Users/mrityunjay/Desktop/XSS/XSS/core/requester.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I have updated pip3, python3 to latest versions, yet.

**Comment by mrityunjay38** [comment]
Note : I have installed remaining files as well. The issue is fixed but I think I need to update geckodriver as well.

**Comment by mrityunjay38** [comment]
Here's the updated error that I am facing now.
<img width="868" alt="Screenshot 2019-05-26 at 18 00 19" src="https://user-images.githubusercontent.com/23267249/58381872-97effc80-7fe0-11e9-978b-c727cc3d5d16.png">

**Comment by s0md3v** [comment]
Install `geckodriver` and Firefox.
