### ISSUE TITLE
Requests Dependency Warning 

### ISSUE THREAD

**Issue by sidjad** [s0md3v/XSStrike#245]
**Describe the bug**

" /usr/lib/python3/dist-packages/requests/__init__.py:80:  urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version! " 

**Screenshots**
![Screenshot from 2019-05-26 21-12-43](https://user-images.githubusercontent.com/3491718/58384162-40f82080-7ffc-11e9-9b94-08a12e8b1237.png)

after I was trying to use with python3.7 other requiredment issue pop-up in terminal 

![Screenshot from 2019-05-26 21-20-00](https://user-images.githubusercontent.com/3491718/58384198-93d1d800-7ffc-11e9-9819-bbf652f72cad.png)

**Environment:**
 - OS: [e.g. Ubuntu 18.04 ]
 - Browser [e.g. Firefox 67.0]
 - Python version [ 3.7]

- [X ] I am using the latest version of XSStrike.
- [ X ] I installed the dependecies using `pip3` instead of `pip`
- [ X ] I have read the documentation before submitting this issue.
- [ X ] I have checked the other issues to see if someone reported this before.

**Comment by s0md3v** [comment]
On the basis of your terminal output, I believe you entered a URL that had multiple parameters in it, separated by `&` e.g. `https://example.com/page.php?q=black&type=shoes`. Bash treats `&` like a special character and hence such URLs should be supplied withing double quotes as follows:

```
python3 xsstrike.py -u "https://example.com/page.php?q=black&type=shoes"
```
