### ISSUE TITLE
false detection simple xss 

### ISSUE THREAD

**Issue by lacroutelacroute** [s0md3v/XSStrike#248]
**Is your feature request related to a problem? Please describe.**
false detection simple xss 

in this webpage

http://reprod.njmu.edu.cn/cgi-bin/2d/2d.cgi?spot=TESTIS_HUMAN:1582&accession=IPI00027264&data=pmf
the first 2 arguments are vulnerable no detection
'"><sVg/oNLoad=prompt()>

**Describe the solution you'd like**
more detection

**Additional context**
python3 --version
Python 3.7.3rc1

$ sudo pip3 install --upgrade -r requirements.txt 
Requirement already up-to-date: selenium in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (3.141.0)
Requirement already up-to-date: tld in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (0.9.3)
Requirement already up-to-date: fuzzywuzzy in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (0.17.0)
Requirement already up-to-date: requests in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (2.22.0)
Requirement already satisfied, skipping upgrade: urllib3 in /usr/lib/python3/dist-packages (from selenium->-r requirements.txt (line 1)) (1.24.1)
Requirement already satisfied, skipping upgrade: six>=1.9 in /usr/lib/python3/dist-packages (from tld->-r requirements.txt (line 2)) (1.12.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 4)) (2018.8.24)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 4)) (2.6)

kali rolling up to date

**Comment by H4sh3** [comment]
Are you owning that domain?
This issues are public, wrong people might find this.

**Comment by lacroutelacroute** [comment]
domain belong to china
APCERT
apcert2018.cert.org.cn
cert.org.cn
I warned them of the vulnerability
this is strict compliance with the law
