### ISSUE TITLE
[Author] Project Update

### ISSUE THREAD

**Issue by s0md3v** [s0md3v/XSStrike#249]
Hello everyone,

I know that I have been inactive for like a month now. I apologize for temporarily abandoning the project after completely rewriting the HTML & JavaScript parsers. I also approved @IAmStoxe's pull requests without testing since he had contributed to project earlier as well.
Both of these changes might have introduced the bugs that were reported in the past month. I believe that was quite irresponsible of me but now I will be working on bug fixes and enhancements with a goal of fixing most of the things within a week.
Thanks for contributing to the project.

Regards,
Somdev Sangwan

**Comment by shadowzoom** [comment]
@IAmStoxe yo can you please make this? https://github.com/s0md3v/XSStrike/issues/206
