### ISSUE TITLE
No reflection  found

### ISSUE THREAD

**Issue by bookchi** [s0md3v/XSStrike#252]
python xsstrike.py -u http://127.0.0.1/dvwa/vulnerabilities/xss_d/?default=English
                                                                                  
        XSStrike v3.1.4                                                           
                                                                                  
[~] Checking for DOM vulnerabilities                                              
[+] WAF Status: Offline                                                           
[!] Testing parameter: default                                                    
[-] No reflection found  

Then, the scan is stopped. Why there is no reflection found?

**Comment by s0md3v** [comment]
Based on the command you have pasted, looks like you didn't supply any cookies.
If that's not the case, let me know and I will re-open this issue and investigate further.

**Comment by bookchi** [comment]
python xsstrike.py -u "http://127.0.0.1/dvwa/vulnerabilities/xss_r/?name=1#" --headers "Cookie: security=low; PHPSESSID=fpd89mr5cjcls56mh2g9b99465"

        XSStrike v3.1.4

[~] Checking for DOM vulnerabilities
[+] WAF Status: Offline
[!] Testing parameter: name
[-] No reflection found

I supply cookie, but it still not works.

**Comment by bookchi** [comment]
Otherwise, it's a reflected XSS actually.

**Comment by hamzaMellahiSenpai** [comment]
@bookchi  did u solve this problem?

**Comment by janoroot** [comment]
python xsstrike.py -u "http://127.0.0.1/dvwa/vulnerabilities/xss_r/?name=1#" --headers "Cookie: security=low; _js_datr=1e0qYI847mFnE5fywK4aLeGA; PHPSESSID=s4268e6srmdet1p4h612ih4tr9" 

The output:

	XSStrike v3.1.4

[~] Checking for DOM vulnerabilities 
[+] WAF Status: Offline 
[!] Testing parameter: name 
[!] Reflections found: 1 
[~] Analysing reflections 
[~] Generating payloads 
[!] Payloads generated: 3072 
------------------------------------------------------------
[+] Payload: <a%09onMoUSeOVer+=+[8].find(confirm)%0dx>v3dm0s 
[!] Efficiency: 100 
[!] Confidence: 10 
[?] Would you like to continue scanning? [y/N] n


I think you need the _js_datr=1e0qYI847mFnE5fywK4aLeGA in the cookie too.

**Comment by windowshopr** [comment]
I have this same issue. Tried running this command:

`python xsstrike.py -u http://172.16.1.82:8008/dvwa/vulnerabilities/xss_d/?Default=English --headers "Cookie: security=low; PHPSESSID m14doqvpdtbvu0039t9m10kmt8"`

I don't have the _js_datr in my cookie in Chrome. A guide on how to use this with the DVWA for newbies would be awesome!

**Comment by isha1701** [comment]
Hi, Please try this:

`python xsstrike.py -u http://localhost/vulnerabilities/xss_r/?name=query --headers "Cookie: security=high; PHPSESSID=vih4oai3maurksimaqvvhdmbd7" --skip-dom`

**Comment by Zavada-Nazarii** [comment]
I can confirm that I experienced the same issue. There was no reflection found despite my use of cookies and header files. Unfortunately, I did not achieve the desired results.

**Comment by yanrbts** [comment]
python3 xsstrike.py -u "http://192.168.3.90:4280/vulnerabilities/xss_r/?name=1#" --headers "Cookie: security=low; PHPSESSID 504b8f12c03878b9317dba31e49819c5" 

[~] Checking for DOM vulnerabilities
[+] WAF Status: Offline
[!] Testing parameter: name
[-] No reflection found

How to use it
