### ISSUE TITLE
Skip other domain

### ISSUE THREAD

**Issue by Turecky** [s0md3v/XSStrike#254]
Bee nice if was possible to set for scanner to check only current domain or add file for domains to skip. If scan domain abc.com i'm not interested to scan googleapis, facebook, twitter etc.

**Comment by s0md3v** [comment]
Hi @Turecky ,

XSStrike doesn't crawl external hosts,
https://github.com/s0md3v/XSStrike/blob/470f138db5fc0943e8a90a0de4052ddb7c03efab/core/photon.py#L63-L65
