### ISSUE TITLE
How to use this tool on an existing app with login?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [s0md3v/XSStrike#258]
I am completely lost on how to use this tool. 
I just keep getting `No parameters to test`. 
How do I facilitate login and crawl all available pages on a website with interaction required to proceed into the web app?

**Comment by Ibrahim-Islam** [comment]
Figured out after some more reading through the issues.

**Comment by markgllin** [comment]
do you happen to have a link to the issue that helped you figure this out?
