### ISSUE TITLE
HEY XSSStrikers Add new feature

### ISSUE THREAD

**Issue by Machineyadav** [s0md3v/XSStrike#268]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
I just love you app. If you will update we will be greatly pleased.
**PLZ HELP BY ADDING FEATURE**
HEY ADD FEATURE OF --cookie parameter beacause you cant test in on many web sites and apps like bWAPP ,dvwa.
1)First install bWAPP and goto Reflected XSS page.
2)Then try using the XSStrike app. It will fail . 
3)Use burp to see the request and find cookie parameter 
4)Download XSSniper app and using --cookie="_cookiedata_" you can find xss vulnerability but doesnt work in XSSstrike app as it doesnt have --cookie feature.Plz make this feature available

**Comment by Machineyadav** [comment]
And mail me if your are thinking to update the app or leave my issue as nonsense.
machinexa@gmail.com

**Comment by s0md3v** [comment]
There is --headers option for that, read the documentation.

**Comment by Machineyadav** [comment]
thanks
