### ISSUE TITLE
BUGS (FIXING WIll GREATLY IMPROVE APPS AND AUDIENCE)

### ISSUE THREAD

**Issue by Machineyadav** [s0md3v/XSStrike#269]
XSSTRIKERS I M BACK WITH BUG
:) :-) :-) :-)
(Before you read create a file xss.txt with one payload (i.e. "><script>alert(1)</script> or anythiig)and xsspayload.txt with lot of payload (100-200) copied from XSS Cheatsheet.
Then try in all levels of bWAPP without -f parameter but with --header parameter with cookie included.Now, after that notice where XSStriker catches XSS and where fasle positive.
Now try it with xss.txt.Notice false positive and resullt.Now with xsspayload.txt. Did XSStriker found out all the correct result.If not correct the bug then try. Make it such a app that it rarely
finds false positives (not a big deal).Also when you take payloads from -f paramter ,take it in such a way that it takes first line as parameter.Then checks then second liine.
HOPE YOU ENJOY THE BUGS)
BUGS:
1)What does [!] and [+] mean.
2)There is no efficiency and confidence when -f param is used.I **_cant tell if my payload works or not_**
3)**_When random code such as <body></body> is used in payload.txt or xss.txt [+] sign is shown ._** Is [+] sign detection of xss. There are lot of false positives even in bWAPP.
4)How to put multiple headers in a single --header “” param..
5)Sometimes, nothing is displayed when -f and --header param are used.At last it says  ~] Bruteforcing [form]: 671/671.it doesnt tell whether xss is detected or not.
5)All the description is given below:- :) :) :) :) :) :) :) :) :) :)
First of all i found a bug. (false positive) . bWAPP is in hardest level i.e security level 2 in bWAPP. so no xss exist(i m referring [+] as xss detection). When testing with this app it shows the following  in screenshot.Secondly if i do that same xss with hard security i.e level=2 without including -f parameter only one false positive gets showed and sometimes none. Now i have screenshot of that also.
The following is first command and all result shows false positive.(i.e xss detected)
 python3 xsstrike.py -u "http://localhost/bWAPP/xss_get.php?firstname=a&lastname=b&form=submit" -f "/root/xsspayloads.txt" --headers "Cookie: PHPSESSID=96uqi98kuf4ceishvadcgqdpr7; security_level=2"
Now second command it display only one xss vuln. sometimes two xss and sometimes none.Work on it. 
python3 xsstrike.py -u "http://localhost/bWAPP/xss_get.php?firstname=a&lastname=b&form=submit" --headers "Cookie: PHPSESSID=96uqi98kuf4ceishvadcgqdpr7; security_level=2
Lastly,
when file xss.txt is selected where xss.txt contains 
-->"><script>alert(1)</script>"><script>alert(1)</script>"><script>alert(1)</script>"><script>alert(1)</script>"><script>alert(1)</script>"><script>alert(1)</script><!--
<body>
</body>
SO, 
<body> 
</body> raised flag. make sure to remove this erroneous bug
NOT ONLY THIS
SUPPOSE I TRY THIS:
WHEN I TRY :
python3 xsstrike.py -u "http://localhost/bWAPP/xss_get.php?firstname=d&lastname=dfd&form=submit" --headers "Cookie: PHPSESSID=96uqi98kuf4ceishvadcgqdpr7; security_level=2" -f "/root/xss.txt"
when xss.txt = "><script>alert(1)</script>
then, + and ! sign are shown.It is also shown in level 1 but not in level 2 but when i use xsspayloads.txt which is a large text file , then every time + and ! sign is shown...What does + and ! sign mean.Similarly,when we use file as parameter confidence and efficiency isnt shown.I cant
tell if payload works or not.No option is shown.

![image](https://user-images.githubusercontent.com/49785874/67616223-c52a1c00-f7c5-11e9-8fa9-5ac4ccd8a9d5.png)
![image](https://user-images.githubusercontent.com/49785874/67616236-ed197f80-f7c5-11e9-8478-7f20f18edae7.png)
![image](https://user-images.githubusercontent.com/49785874/67616247-05899a00-f7c6-11e9-88c8-acbb397e072b.png)
![image](https://user-images.githubusercontent.com/49785874/67616250-1afec400-f7c6-11e9-8d27-7251fe3ca98a.png)
![image](https://user-images.githubusercontent.com/49785874/67616252-27831c80-f7c6-11e9-93e8-6a5cc8a3db12.png)

**Comment by Machineyadav** [comment]
Mail me if you are interested in fixing bug or mail me if you think i m just a prankster disturbing you guys :-) 
mailto:machinexa@gmail.com

**Comment by s0md3v** [comment]
:man_facepalming:

**Comment by Machineyadav** [comment]
Did u solved the bug?thanks for commenting
