### ISSUE TITLE
fuzzywuzzy isn't installed

### ISSUE THREAD

**Issue by shahbaz883** [s0md3v/XSStrike#270]
C:\PentestBox\XSStrike
> xsstrike.py

        XSStrike v3.1.4

[!] fuzzywuzzy isn't installed, installing now.
'pip3' is not recognized as an internal or external command,
operable program or batch file.
[!] fuzzywuzzy has been installed, restart XSStrike.

**Comment by s0md3v** [comment]
install `pip3` first

**Comment by freekey000** [comment]
oot@kali:~/XSStrike# python3 xsstrike.py -h

	XSStrike v3.1.4

[!] fuzzywuzzy isn't installed, installing now.
Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.8/dist-packages (0.17.0)
[!] fuzzywuzzy has been installed, restart XSStrike.

**Comment by 1UC1F3R616** [comment]
@freekey000 did you find a solution for this?
- I deactivated and then again activated my venv but that didn't helped me :/

**Comment by RBloemers** [comment]
same on osx here

**Comment by merianos** [comment]
Have the same problem with @RBloemers

**Comment by SSSEAL-C** [comment]
Any fix for this? Still a problem for me... and pip3 is installed.

**Comment by sharikovvladislav** [comment]
I have the same problem.

**Comment by iamuk** [comment]
sudo apt-get  install python3-fuzzywuzzy should fix it
