### ISSUE TITLE
Hi  i am not sure if this is ok 

### ISSUE THREAD

**Issue by IamAhacker1345693** [s0md3v/XSStrike#275]
hi ,   i got this payload }]};(confirm)()//\ and it said that is valid , but nothing is going to happen to the actual website

**Comment by Liza898** [comment]
> hi , i got this payload }]};(confirm)()//\ and it said that is valid , but nothing is going to happen to the actual website

yep. Maybe it was a false check of the site's vulnerability. I've had the same thing.

**Comment by adi928** [comment]
You need to provide logs of what you've tried for us to help you. You can geenrate that by running your script with this option:
`--log-file` where default file is already hardcoded.

**Comment by s0md3v** [comment]
not enough info.
