### ISSUE TITLE
NOt sure 2

### ISSUE THREAD

**Issue by IamAhacker1345693** [s0md3v/XSStrike#276]
<dEtAILS%09onpointEREnteR%0a=%0a[8].find(confirm)%0dx// 

what is this do ??? and how i know it worked ??? please respond fast !!! thanks

**Comment by adi928** [comment]
First of all this isn't an issue with the tool. Second of all, you really need to gain exposure in XSS for even understanding the answer to your question. This may help:
https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet
