### ISSUE TITLE
Cookie Support on Windows

### ISSUE THREAD

**Issue by Z0rkan** [s0md3v/XSStrike#28]
Hey Guys,

Can you update please what is the correct syntax to add cookie to the request?
The current cookie is as follows: 
`qa=WSAFEDADDFDFDFDF363DD6903C7D33875645B460A08CBCD4C918B1GFGDGJHDSD435345345435C3FFDBB66874074578B59EA0D; __RequestVerification=2Ksdf5UKbXSr_Moxq59OjbghgKpCHENwf; path=/; domain=qa.example.com;`

I've tried using brackets, semicolon etc with no luck.

Thanks!
Z0rkan

**Comment by UltimateHackers** [comment]
Hi there,
Is XSStrike throwing any error after entering the cookie or the cookie _just doesn't work_?

**Comment by GrayDigital** [comment]
Hi @s0md3v ,

I am Also facing the same issue.

I am getting the following error:
xsstrike.py: error: unrecognized arguments: --Cookie:ASP.NET_SessionId=ymo1ddzzrd20rxz2irkvzr2m

**Comment by s0md3v** [comment]
Hi @GrayDigital ,

It is to let you know that your issue has been acknowledge and is being worked on.
You can expect a patch soon.

**Comment by s0md3v** [comment]
Hi @GrayDigital ,

I suggest you to go through XSStrike's documentation.
Anyway, you can use the `--headers` switch will open a prompt like the one below where you can paste your headers:

![headers](https://image.ibb.co/jw5NgV/Screenshot-2018-10-27-18-45-32.png)

**Comment by Maskhe** [comment]
So,it seems like that there isn`t cookie support on windows

**Comment by s0md3v** [comment]
@Maskhe You will get it today :+1:
