### ISSUE TITLE
Both payload "><script>alert(1)</script> and DDD shows same output. Difficult to know whether payload works or not

### ISSUE THREAD

**Issue by warmachine-pixel** [s0md3v/XSStrike#287]
Hey bro app, Doesnt show efficiency and confidence when using manual wordlist.
![image](https://user-images.githubusercontent.com/59498388/71762473-7075e200-2e95-11ea-9e08-4f6d68000a91.png)
And the content of file XSSs.txt is DDDD which is not a payload still it shows [!] and [+] sign which was on  "><script>alert('1')</script> 
 too.
![image](https://user-images.githubusercontent.com/59498388/71762514-d1051f00-2e95-11ea-92d1-bfd0c39bdca8.png)

**Comment by warmachine-pixel** [comment]
Sorry its supported

**Comment by s0md3v** [comment]
If its green, its not being filtered. If its red, its being filtered.
