### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by jepunband** [s0md3v/XSStrike#292]
**Describe the bug**

Traceback (most recent call last):
  File "xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, find, skip)
  File "/mods/git/XSStrike/modes/scan.py", line 48, in scan
    params = getParams(target, paramData, GET)
  File "/mods/git/XSStrike/core/utils.py", line 165, in getParams
    data = url.split('?')[1]
IndexError: list index out of range

**To Reproduce**

python3 xsstrike.py -u https://somewebsite.com/blog/search/query=

Explain how the issue can be reproduced.

**Screenshots**
If applicable, add screenshots or paste terminal output to help explain your problem.
Feel free to hide sensitive information like the URL of the target.

**Potential cause or fix**
Do you know what could be causing the problem or how to fix it?

**Environment:**
 - OS: [e.g. Kali Rolling 2018.2]
 - Browser [e.g. Firefox 60.2]
 - Python version [e.g. 3.7]

**Some Questions**

- [ X ] I am using the latest version of XSStrike.
- [ x ] I installed the dependecies using `pip3` instead of `pip`
- [ x ] I have read the documentation before submitting this issue.
- [ x ] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?

**Comment by sir-marv** [comment]
Can confirm, same issue here.

Running in Docker python:3-alpine

**Comment by s0md3v** [comment]
Fixed.
