### ISSUE TITLE
some bug in crawl.py

### ISSUE THREAD

**Issue by liuyuying123** [s0md3v/XSStrike#296]
**Describe the bug**
recently I read the source code and found that in crawl.py,in line 46
the code is :efficiencies = filterChecker(url, paramsCopy, headers, GET, delay, occurences, timeout, encoding)
it adds the char score in occurences,then next line is :vectors = generator(occurences, response.text)
so i think in this line ,'occurences' should be 'efficiencies'

if I'm wrong ,i'm sorry,but i'm learning this project seriously,thank you very much!

**Comment by s0md3v** [comment]
Fixed, thanks.
