### ISSUE TITLE
Wrong message being displayed when pip3 not installed

### ISSUE THREAD

**Issue by networknerd** [s0md3v/XSStrike#303]
**Description**
When pip3 is not installed on the system before running xsstrike script, the installation of fuzzywuzzy is failing but the message displayed is "fuzzywuzzy has been installed, restart XSStrike.". Upon rerunning, the same issue is encountered.

**To Reproduce**
Clone the Xsstrike repo onto a ubuntu system which does not have pip3 and fuzzywuzzy installed and run the xsstrike.py script

**Screenshots**
```
vagrant@ubuntu-xenial:/vagrant/XSStrike$ python3 xsstrike.py -u https://public-firing-range.appspot.com/reflected/parameter/tagname

	XSStrike v3.1.4

[!] fuzzywuzzy isn't installed, installing now.
sh: 1: pip3: not found
[!] fuzzywuzzy has been installed, restart XSStrike.
vagrant@ubuntu-xenial:/vagrant/XSStrike$ python3 xsstrike.py -u https://public-firing-range.appspot.com/reflected/parameter/tagname

	XSStrike v3.1.4

[!] fuzzywuzzy isn't installed, installing now.
sh: 1: pip3: not found
[!] fuzzywuzzy has been installed, restart XSStrike.
```
**Potential cause or fix**
Check for the existence of pip3 on the system when trying to install fuzzywuzzy and print appropriate message if pip3 is not present

**Environment:**
 - OS: Ubuntu Xenial
 - Hosted using Vagrant 

**Some Questions**

- [x] I am using the latest version of XSStrike.
- [x] I installed the dependecies using `pip3` instead of `pip`
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?

**Comment by networknerd** [comment]
#304

**Comment by akernelpanicv** [comment]
Hey. I think you can create a virtual environment for this project, then activate it and use `pip install fuzzywuzzy` in your venv. I hope this will help you!

**Comment by RolEYder** [comment]
Try to run it again in a root user.

**Comment by fahmiarieframdan** [comment]
good
