### ISSUE TITLE
Every payload that XSStrike is showing is false positive?

### ISSUE THREAD

**Issue by FaizanNehal** [s0md3v/XSStrike#307]
I have tested several website with this tool, it usually dozens of payloads with efficiency of more than 90 and confidence of 10, But none of them usually works. Do you thing am I missing something?
I usually run the payload by copying it and pasting as it is in the URL like for example
The URL is `example.com/search?q=`
and payload shown by this tool is `xxxxxxxxx` 
The URL that I run will be `example.com/search?q=xxxxxxxxx `
The payloads never works

**Comment by aman566** [comment]
It will. Try to inject other payloads manually.

**Comment by s0md3v** [comment]
Some of them require user interaction.
