### ISSUE TITLE
script failed to run in virtual environment

### ISSUE THREAD

**Issue by 1UC1F3R616** [s0md3v/XSStrike#308]
**Describe the bug**
- When running script in virtual env then getting below error every time
```
        XSStrike v3.1.4

[!] fuzzywuzzy isn't installed, installing now.
Requirement already satisfied: fuzzywuzzy in e:\pentest_tools\venv\lib\site-packages (0.18.0)
[!] fuzzywuzzy has been installed, restart XSStrike.
```
- Script doesn't execute further
- I ran it without using virtual env then it worked as expected

**To Reproduce**
- create virtual env: `py -m venv env`
- install dependencies `py -m pip install -r requirements.txt` *(For me it's pip, not pip3, even the main dependencies use this only)*
- activate the virtual env
- run the script `xsstrike.py -u "https://xss-game.appspot.com/level1/frame?query=query"`

**Environment:**
 - OS: Windows version 1909
 - Python version: 3.7.3

- [x] I am using the latest version of XSStrike.
- [x] I installed the dependencies using `pip3` instead of `pip`
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

*hey, correct the spelling of dependencies in the bug report 😄 :*

**Comment by s0md3v** [comment]
Make sure your PATH is set up correctly, XSStrike should be able to import those dependencies to run.
