### ISSUE TITLE
Crawling the target: Progress 1/1

### ISSUE THREAD

**Issue by Arnauec-zz** [s0md3v/XSStrike#316]
**Describe the bug**
When testing a webpage the tool says Progress 1/1 and then it dies without giving any type of error.

**To Reproduce**
Sadly can't post it here as we are using the tool to test a pre-production site and we can't disclose it publicly, have contacted you via Twitter in case you can have a look at this with me. 

**Screenshots**
If applicable, add screenshots or paste terminal output to help explain your problem.
Feel free to hide sensitive information like the URL of the target.
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/22740717/99653003-cd9c6700-2a58-11eb-95d7-04acc82dc3ca.png">

**Potential cause or fix**
Do you know what could be causing the problem or how to fix it?
I think the reason why this is happening is because the website is PWA with a headless approach (https://www.vuestorefront.io/) and the tool is having a hard time understanding how the webpage works.

**Environment:**
 - OS: [e.g. Kali Rolling 2018.2]
 - Browser [e.g. Firefox 60.2]
 - Python version [e.g. 3.7]

**Some Questions**

- [x] I am using the latest version of XSStrike.
- [x] I installed the dependecies using `pip3` instead of `pip`
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?

**Comment by MilkshakeMan69** [comment]
I got the same error and don't know how to fix. It works if i give it an operand at the end of the URL but that's the whole point missed.
![yzix9e5j2g181](https://user-images.githubusercontent.com/68537767/143215646-b2e6a3e4-dae5-4957-b567-745b033ab4dc.png)
.
