### ISSUE TITLE
failing to complete scan

### ISSUE THREAD

**Issue by Jasperboots** [s0md3v/XSStrike#319]
when i run a basic scan on a url and it finds reflections it asks me to press y and when i do it stops and gives me this:
<pre>?] Would you like to continue scanning? [y/N] y
y: command not found

[1]+  Stopped         
</pre>

not sure if this happens with other sites as i've only run it on the one that was successful so far but if its just the one site ill email, however im wondering if im having a syntax issue idk

**Environment:**
 - OS: [ubuntudde 20.10]

 - Python version [ 3.9]

- [ x] I am using the latest version of XSStrike.
- [ x] I installed the dependecies using `pip3` instead of `pip`
- [ x] I have read the documentation before submitting this issue.
- [ x] I have checked the other issues to see if someone reported this before.

**Comment by s0md3v** [comment]
Looks like you didn't put the URL within double quotes.
