### ISSUE TITLE
How to restart XSStrike ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [s0md3v/XSStrike#322]
My current problem is when i install XSStrike everything runs good then it needs to get the fuzzer installed. Now it says to restart how do you restart xsstrike in the command line ?

**[!] fuzzywuzzy isn't installed, installing now.
Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0
[!] fuzzywuzzy has been installed, restart XSStrike.
kali@kali:~/XSStrike$**

**Comment by AlenJungle** [comment]
I have the same problem,do you slove this? help me please.
