### ISSUE TITLE
IndexError 

### ISSUE THREAD

**Issue by pseudog0d** [s0md3v/XSStrike#329]
**Describe the bug**
While trying to normally use the tool today, with a specific website I get an IndexError.

**To Reproduce**
Explain how the issue can be reproduced.
python3 ./xsstrike.py -u "https://someurl.com/search.html#q=some_query" 

This happens only with a specific website. 

**Screenshots**
If applicable, add screenshots or paste terminal output to help explain your problem.
Feel free to hide sensitive information like the URL of the target.
![image](https://user-images.githubusercontent.com/65175780/130347945-6c8c4c46-c921-4721-9d35-c5847b388ebf.png)

**Potential cause or fix**
Do you know what could be causing the problem or how to fix it?
I believe the error arises due to the ".html" portion in the specific URL.

**Environment:**
 - OS: [e.g. Kali Rolling 2018.2] Ubuntu 
 - Browser [e.g. Firefox 60.2] Firefox 91.0.1
 - Python version [e.g. 3.7] 3.9.5

**Some Questions**

- [ x] I am using the latest version of XSStrike.
- [x ] I installed the dependecies using `pip3` instead of `pip`
- [x ] I have read the documentation before submitting this issue.
- [ x] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?

**Comment by terminalJunki3** [comment]
Looks like it's trying to slit the URL using "?", but the URL doesn't have any parameters.

**Comment by its0x08** [comment]
Add a `?` After the `#`

**Comment by s0md3v** [comment]
Fixed.
