### ISSUE TITLE
Unrecognised Argument on Web Application

### ISSUE THREAD

**Issue by aldooonih** [s0md3v/XSStrike#332]
Hello, I'm new into this and getting some error. So i have a python 3.4, and trying to run XSStrike on CMD, using windows 7 32 bit. 

![Capture](https://user-images.githubusercontent.com/90582590/133040306-c40f7d8f-843d-47f5-adea-9fa4698c319b.JPG)

The images above shows that when i try to scan on a web application, and it says if the web application is unrecognized argument. 

I got no idea what i should do next, 

> Anyway, it happens to every website that I tried to scan, like the one below:

![Capture](https://user-images.githubusercontent.com/90582590/133040879-5f063aac-1984-4ea2-b7c2-3b7d90053496.JPG)

**Comment by s0md3v** [comment]
You copied a unicode character `\u2013u` by mistake
