### ISSUE TITLE
fuzzywuzzy has been installed, restart XSStrike.

### ISSUE THREAD

**Issue by mkkurt** [s0md3v/XSStrike#335]
**Describe the bug**
When i run the program it says "fuzzywuzzy isn't installed, installing now." and then "fuzzywuzzy has been installed, restart XSStrike."

**To Reproduce**
Run xsstrike.py on Windows 10 (Python 3.10)

**Screenshots**
If applicable, add screenshots or paste terminal output to help explain your problem.
Feel free to hide sensitive information like the URL of the target.

**Potential cause or fix**
Do you know what could be causing the problem or how to fix it?

**Environment:**
 - OS: Win10
 - Python version 3.10

**Some Questions**

- [x ] I am using the latest version of XSStrike.
- [x ] I installed the dependecies using `pip3` instead of `pip`
- [x ] I have read the documentation before submitting this issue.
- [x ] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?

**Comment by Ghoul149** [comment]
Fuzzywuzzy is the python based external library which is needed to run this code and to install fuzzywuzzy please follow the steps given below:
1)Open CMD
2) type python and the cmd will display the python version and the installed directory.
3) Type "pip install fuzzywuzzy"
After some moments the library called fuzzywuzzy will be installed in your local system .
If you face any more queries regarding it you are free to comment down here..
Thanks
Ghoul149<vkanjaria99@gmail.com>

**Comment by load-net** [comment]
(wapiti3) D:\python\wapiti3>pip3 install -r requirements.txt
Requirement already satisfied: tld in d:\python\wapiti3\lib\site-packages (from -r requirements.txt (line 1)) (0.12.6)
Requirement already satisfied: fuzzywuzzy in d:\python\wapiti3\lib\site-packages (from -r requirements.txt (line 2)) (0.18.0)
Requirement already satisfied: requests in d:\python\wapiti3\lib\site-packages (from -r requirements.txt (line 3)) (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in d:\python\wapiti3\lib\site-packages (from requests->-r requirements.txt (line 3)) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in d:\python\wapiti3\lib\site-packages (from requests->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\python\wapiti3\lib\site-packages (from requests->-r requirements.txt (line 3)) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\python\wapiti3\lib\site-packages (from requests->-r requirements.txt (line 3)) (1.26.12)

(wapiti3) D:\python\wapiti3>xsstrike.py -u "http://10.20.7.104" --blind

        XSStrike v3.1.5

[!] fuzzywuzzy isn't installed, installing now.
Requirement already satisfied: fuzzywuzzy in d:\python\wapiti3\lib\site-packages (0.18.0)
[!] fuzzywuzzy has been installed, restart XSStrike.

(wapiti3) D:\python\wapiti3>
exit   no work

**Comment by sharikovvladislav** [comment]
I have the same.
