### ISSUE TITLE
Import Requests issue

### ISSUE THREAD

**Issue by Ghoul149** [s0md3v/XSStrike#336]
The program firstly install the fuzzywuzzy library and then it shows an unnamed error of import requests failed...

**To Reproduce**
Firstly running the .py files of the program and then it directly installs the required libraries automatically and the shows and error that the import requests file is missing from the directory....

**Potential cause or fix**
merging the request files (missing one) onto the original bench will make a solution 

**Environment:**
 - OS: Windows 10
 - Browser chrome(latest)
 - Python version [v3.10]

**Some Questions**

- [x] I am using the latest version of XSStrike.
- [x] I installed the dependecies using `pip3` instead of `pip`
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

**Other comments**
Do you have something else to say?
NO .....

**Comment by s0md3v** [comment]
It's upto the user to install the dependency.
