### ISSUE TITLE
XSStrike fails to find XSS sinks like `document.write`, `.innerHTML` and `eval`

### ISSUE THREAD

**Issue by KartikSoneji** [s0md3v/XSStrike#341]
**Describe the bug**
XSStrike fails to find XSS sinks like `document.write`, `.innerHTML` and `eval`.

**To Reproduce**
Explain how the issue can be reproduced.
Setup:

1. Create `index.html`
```html
<!DOCTYPE html>
<html>
    <body>
        <div>
            <pre>document.writeln(new URL(window.location.href).searchParams.get("a"))</pre>
            <script>document.writeln(new URL(window.location.href).searchParams.get("a"))</script>
        </div>
        <div>
            <pre>document.write(new URLSearchParams(window.location.search).get("b"))</pre>
            <script>document.write(new URLSearchParams(window.location.search).get("b"))</script>
        </div>
        <div>
            <pre>eval(new URLSearchParams(window.location.search).get("c") || "")</pre>
            <script>eval(new URLSearchParams(window.location.search).get("c") || "")</script>
        </div>
        <div>
            <div id="xss-d"></div>
            <pre>document.querySelector("#xss-d").innerHTML = new URLSearchParams(window.location.search).get("d")</pre>
            <script>document.querySelector("#xss-d").innerHTML = new URLSearchParams(window.location.search).get("d")</script>
        </div>
    </body>
</html>
```

2. Run `python3 -m http.server`

3. Run `python3 xsstrike.py`

**Screenshots**
```console
> python3 xsstrike.py -u "http://localhost:8000/?a=a&b=b&c="

        XSStrike v3.1.4

[~] Checking for DOM vulnerabilities 
[+] WAF Status: Offline 
[!] Testing parameter: a 
[-] No reflection found 
[!] Testing parameter: b 
[-] No reflection found 
[!] Testing parameter: c 
[-] No reflection found 
[!] Testing parameter: d 
[-] No reflection found 
```

`--fuzzer` also does not work.

**Potential cause or fix**
> Do you know what could be causing the problem or how to fix it?

A potential way could be to mark sinks like `document.write`, `document.writeln`, `.innerHTML` and `eval`.  
Even if they can't be explored automatically, they can be flagged for manual review.

**Environment:**
```console
> lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

> firefox --version
Mozilla Firefox 98.0.1

> python3 --version
Python 3.8.10
```

**Some Questions**

- [x] I am using the latest version of XSStrike.
- [x] I installed the dependecies using `pip3` instead of `pip`
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.
  Related issue: #81 

**Other comments**
Haven't got a chance to use the tool extensively but looks great!

**Comment by s0md3v** [comment]
Fixed.
