### ISSUE TITLE
XSStrike keeps trying to install fuzzywuzzy and wont start normally

### ISSUE THREAD

**Issue by RalkeyOfficial** [s0md3v/XSStrike#344]
I followed the FAQ and installed fuzzywuzzy with pip3

i tried using XSStrike again, but it keeps telling me "Requirement already satisfied"
and that I have to restart XSStrike (which doesnt do anything)

**Comment by coderscoding** [comment]
It works for me 

first run this `/usr/bin/python3 -m pip install fuzzywuzzy`
install any-other module similar way

then run `/usr/bin/python3 xsstrike.py`
