### ISSUE TITLE
Could not connect to the target

### ISSUE THREAD

**Issue by neomh** [s0md3v/XSStrike#37]
Hello

I'm using a system behind a proxy. How to include proxy in the code ?

Thank you

**Comment by UltimateHackers** [comment]
This is a beta release and such features will be include after a stable release :)

**Comment by neomh** [comment]
Thank you for your response. I managed to get it to work using cntlm and export_proxy. You also have to run the python command using sudo -E

**Comment by ZigmundVonZaun** [comment]
I addes SOCKS5 proxy support into the script. PR #44 You can also use Tor by installing a local or remote daemon and referencing it like so: ```socks5h://localhost:9050```. Thank you

**Comment by ishaa-09** [comment]
whichever target i put it shows [!!] Unable to connect to the target. What can be the problem?

**Comment by Muraeanone** [comment]
> whichever target i put it shows [!!] Unable to connect to the target. What can be the problem?
> 

I need the answers to
