### ISSUE TITLE
Second-Order XSS

### ISSUE THREAD

**Issue by slinkymanbyday** [s0md3v/XSStrike#38]
Would it be possible to support second order XSS? That is inject the payload on X URL, and then check Y to see if injection is successful where Y could even be seperate domain.

**Comment by UltimateHackers** [comment]
Hi there,
Thanks for suggestion, its a good one but for now my priority is to release a stable build.
After that I will be working on features like crawling, encoding support etc.
I am keeping this issue open and lets hope that it will be closed soon ;)

**Comment by s0md3v** [comment]
So I thought about it and concluded that there's no place for such specific context based features in XSStrike when there are already a lot of bugs to fix & important features to add.
Thanks for the suggestion tho, I may give it another thought later.
