### ISSUE TITLE
Unable to connect to the target 

### ISSUE THREAD

**Issue by foudadev** [s0md3v/XSStrike#384]
** runtime error**
# command used
> python3 xsstrike.py -u "http://94.237.62.195:59433/?fullname=test&username=test&password=test&email=t@t.com"
## error i got 
Traceback (most recent call last):
  File "/Users/$user/XSStrike/xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "/Users/$user/XSStrike/modes/scan.py", line 52, in scan
    WAF = wafDetector(
  File "/Users/$user/XSStrike/core/wafDetector.py", line 25, in wafDetector
    if int(code) >= 400:
ValueError: invalid literal for int() with base 10: 'None'

finally thanks for your great job

**Comment by stedlan** [comment]
Iam facing the same problem

**Comment by Cy-Beard** [comment]
I get the same error as well. Is it if there is a WAF in front it fails?

**Comment by foudadev** [comment]
@stedlan  @Cy-Beard  the problem is solved to me try 
```
 cd XSStrike
python3 xsstrike.py -u "https://Domain/?paramter=test"
```

**Comment by Ahmed222234** [comment]
I have the same error even when i use this command  cd XSStrike
python3 xsstrike.py -u "https://Domain/?paramter=test"
how can i solve this problem??
@foudadev

**Comment by ShortTimeNoSee** [comment]
I'm experiencing this issue in the latest version. When the WAF probe is sent (`<script>alert("XSS")</script>`), some targets hard-drop the connection without sending a status line. This leaves `response.status_code` as `None`, which causes `wafDetector()` to do:

```
code = str(response.status_code)  # 'None'
int(code)  # ValueError
```

Even if `requester()` catches the `requests` exception it currently returns a "response" without a valid status code, so the crash is inevitable.

```
Traceback (most recent call last):
  File "D:\Projects\Attack\XSStrike\xsstrike.py", line 174, in <module>
    scan(target, paramData, encoding, headers, delay, timeout, skipDOM, skip)
  File "D:\Projects\Attack\XSStrike\modes\scan.py", line 52, in scan
    WAF = wafDetector(
  File "D:\Projects\Attack\XSStrike\core\wafDetector.py", line 25, in wafDetector
    if int(code) >= 400:
ValueError: invalid literal for int() with base 10: 'None'
```
