### ISSUE TITLE
Using slow pure-python SequenceMatcher.

### ISSUE THREAD

**Issue by iamkenichi** [s0md3v/XSStrike#39]
Hi s0md3v,

I'm just wondering if we can silence this warning?

/usr/local/lib/python2.7/site-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

**Comment by swifhorse119812** [comment]
pip install python-Levenshtein
