### ISSUE TITLE
"Unable to connect to target"

### ISSUE THREAD

**Issue by Throwaway1967** [s0md3v/XSStrike#395]
Whenever I try a website using "python3 xsstrike.py -u https://example.com/ --crawl --blind", I get the output:
	XSStrike v3.1.5

 Crawling the target 
------------------------------------------------------------
 Vulnerable component: jquery v3.5.1 
 Component location: https://example.com/js/ST/jquery-3.5.1.min.js 
 Total vulnerabilities: 0 
------------------------------------------------------------
------------------------------------------------------------
 Vulnerable component: bootstrap v3.4.1 
 Component location: https://example.com/js/ST/bootstrap.min.js 
 Total vulnerabilities: 0 
------------------------------------------------------------
[!!] Unable to connect to the target.            
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 
[!!] Unable to connect to the target. 

Any ideas why? I'm on a mac with all the dependencies installed and other commands work fine.

**Comment by krivadna** [comment]
I am getting the same. No tool will work as most tools getting Deprecated.. Algorithm changing everyday.. Nothing will work next day..

**Comment by krivadna** [comment]
Nuclei 
Gobuster

Nothing is working.. 

Nothing at all.. They are changing everything...

**Comment by darkb0ts** [comment]
XSstrike only includes some outdated payloads. If you're looking for a more updated tool, consider using Xray (https://github.com/chaitin/xray) or Nuclei.

**Comment by reevesy1** [comment]
have you tried with and without https:// or http:// at the start. Is the url live?

I use this command 
``` while read -r url; do
python3 xsstrike.py -l 3 -u "$url"; done < "list-of-urls-to-test.txt"
```

**Comment by Throwaway1967** [comment]
> have you tried with and without https:// or http:// at the start. Is the url live?
> 
> I use this command
> 
> ```
> while read -r url; do
> python3 xsstrike.py -l 3 -u "$url"; done < "list-of-urls-to-test.txt"
> ```
> 
> thats in a script but should work
> 
> ```
> while read -r url; do; python3 xsstrike.py -l 3 -u "$url"; done < "list-of-urls-to-test.txt"
> ```

Thank you so much! For whatever reason your command works but mine doesn't. Maybe it's my laptop or part of a wider problem, but either way it works now.

**Comment by krivadna** [comment]
Doesn't work...this tool doesn't work for most of people

**Comment by krivadna** [comment]
> XSstrike only includes some outdated payloads. If you're looking for a more updated tool, consider using Xray (https://github.com/chaitin/xray) or Nuclei.

No brother. imhave trouble with xray too..it's binary doesn't get installed whether use git clone or download and extract the file
