### ISSUE TITLE
No module named parse

### ISSUE THREAD

**Issue by iamkenichi** [s0md3v/XSStrike#41]
This happened after the latest update

Traceback (most recent call last):
  File "xsstrike", line 17, in <module>
    from urllib.parse import urlparse, parse_qs, quote_plus
ImportError: No module named parse

**Comment by jaywon** [comment]
PR #42 will fix this issue

**Comment by s0md3v** [comment]
Hi there,
Thanks for reporting the issue.
Python2 support has been dropped in the latest update and XSStrike now runs on Python3.
Try running XSStrike with python3 as follows
`python3 xsstrike`
Let me know if the issue persists.
Thanks again.

**Comment by s0md3v** [comment]
Sorry for that, I closed it unknowingly.
