### ISSUE TITLE
Find Python3 replacement for mechanize module

### ISSUE THREAD

**Issue by jaywon** [s0md3v/XSStrike#43]
The mechanize dependency is *only* supported in Python 2.7 with documented resistance to putting out a Python 3 compatible version. This prevents the project from offering full Python 3 support.

**Comment by s0md3v** [comment]
XSStrike doesn't use mechanize anymore, it has been replaced by [requests](https://github.com/requests/requests).

**Comment by jaywon** [comment]
Haha gotcha, I pulled this morning before your last commit. Looks good now, able to install and run w/ no issues 👍 🎉
