### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by VIRTU4LC0D3R** [s0md3v/XSStrike#45]
error 👍 
(https://user-images.githubusercontent.com/37764006/41677652-87fb6856-74e6-11e8-97fa-397992932a96.jpeg)
pip install -r requirements.txt 

and getting error when try to open the pkg file . try to open with python , python2 , python3 but not opening. it showing module error 
(https://user-images.githubusercontent.com/37764006/41677720-c0516502-74e6-11e8-8b8e-8abd7de5828a.jpeg)

**Comment by umakantabehera** [comment]
@VIRTU4LC0D3R I'm facing same issue while installing in termux. Could you please let us know if this issue was resoved ?

**Comment by s0md3v** [comment]
@umakantabehera
Run XSStrike with `python3` and if it throws any error about a missing module, install the module with `pip3`.

**Comment by umakantabehera** [comment]
@s0md3v 
I tried with "pip3 install -r requirements.txt" with chmod +x , but getting the same error.
Am I missing something else ?

**Comment by s0md3v** [comment]
@umakantabehera
1. You don't need to `chmod` python scripts
2. Don't install stuff from requirements.txt, do what I said in previous comment.

**Comment by umakantabehera** [comment]
Thanks so much! @s0md3v 
It worked!
