### ISSUE TITLE
POST with data in URL

### ISSUE THREAD

**Issue by Hipapheralkus** [s0md3v/XSStrike#49]
Is it possible to scan a request which needs to have data in both URI as well as body? When I transform request to GET, or move all the parameters into POST, the tested website doesn't work. Hence I need to be able to instruct XSStrike to use both parameters in POST body as well as URI. At this moment, I don't see the option.

**Comment by s0md3v** [comment]
The Zen of python says:

> Special cases aren't special enough to break the rules.

That's what I believe in, the website you are talking about is a special case and I can't change XSStrike's workflow for that, you should modify the code on your copy. Let me know if you need any help in that.
