### ISSUE TITLE
Loading request from file

### ISSUE THREAD

**Issue by Hipapheralkus** [s0md3v/XSStrike#50]
The SQLmap has a great functionality of being able to use the request from file. Is it possible to implement something like that for XSStrike? I can see an example where language from "Accept-Language" is reflected back from the server within the HTTP response. Also, it would ease up integration with other tools or usecases, like using POST with data in URI + body.

**Comment by s0md3v** [comment]
[XSStrike v3.0's code and workflow is totally different from v2.0 so the issue doesn't hold anymore.]

**Comment by Hipapheralkus** [comment]
I'm sorry, I disagree. I would still love the tool to be able to parse everything from request file. At the moment, my session cookie looks like 
`JSESSIONID=8W21z5LC9dIK50cuJDLev4wLwbhZneSdTVF7eW-U4bPTJXZv6zdN!-12271112;`
and I'm not able to write cookie syntax properly so that my session works. That being said, some logging with more information would be useful for debugging requests...

**Comment by s0md3v** [comment]
@Hipapheralkus XSStrike now has a interactive prompt for supplying HTTP headers.

Option: `--headers`

This option will open your text editor (default is 'nano') and you can simply paste your HTTP headers and press `Ctrl + S` to save.

![headers demo](https://image.ibb.co/jw5NgV/Screenshot-2018-10-27-18-45-32.png)
