### ISSUE TITLE
False negative report

### ISSUE THREAD

**Issue by Hipapheralkus** [s0md3v/XSStrike#51]
Hi,
I wanted to use XSStrike on XSS I found, but it didn't recognize it. As you can see on the piucture, it's a very simple GET with a single parameter returned in the response. No WAF, no output encoding, no session required.
![image](https://user-images.githubusercontent.com/4717664/42619061-426e605e-85b7-11e8-9ec9-999b9ed4598f.png)

**Comment by s0md3v** [comment]
Hi there,

This seems like a serious bug.
I know I am asking for too much but can you mail me the website you are testing so I can see what's wrong?
Thanks.

**Comment by Hipapheralkus** [comment]
I'm afraid I can't do that, as it is an internal application without access to the internet

**Comment by s0md3v** [comment]
Ah alright, do you have a twitter or telegram? I need some debugging output from your side to figure out what's wrong.

**Comment by s0md3v** [comment]
This issue will be closed after 24 hours due to inactivity :)

**Comment by s0md3v** [comment]
Time's up :)

**Comment by gauravlinux** [comment]
if ( /world101\.cfr\.org/.test(window.location.href) ) {
------------------------------------------------------------
[-] WAF detected: CloudFlare Web Application Firewall (CloudFlare) 
[!] Testing parameter: keywords 
[!] Reflections found: 2 
[~] Analysing reflections 
[~] Generating payloads 
[!] Payloads generated: 5 
 ~] Progress: 5/5
                    payload    ?????
