### ISSUE TITLE
Incorrectly parsed parameters names?

### ISSUE THREAD

**Issue by Hipapheralkus** [s0md3v/XSStrike#52]
I noticed that many times when I try to discover parameters, there is a '>' character at the end. Not sure if the parameter name is being parsed incorrectly, or just its representation in GUI:
![image](https://user-images.githubusercontent.com/4717664/42619779-4fce758e-85b9-11e8-9fc0-152972e2f65e.png)
The HTML looks like this:
![image](https://user-images.githubusercontent.com/4717664/42619943-bdf49a48-85b9-11e8-8c15-36a28e034757.png)

**Comment by s0md3v** [comment]
Thanks for reporting, I will look into it.

**Comment by s0md3v** [comment]
Hi @Hipapheralkus ,
Can you please confirm the patch? Thanks.
