### ISSUE TITLE
ModuleNotFoundError: No module named 'fuzzywuzzy'

### ISSUE THREAD

**Issue by SedatOzdemir** [s0md3v/XSStrike#61]
Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python2.7/dist-packages

How can I fix this ? :(

**Comment by s0md3v** [comment]
XSStrike is not compatible with `python2`, please run it with `python3` and install the required modules with `pip3` instead of `pip`.

**Comment by Pwang001** [comment]
> XSStrike is not compatible with `python2`, please run it with `python3` and install the required modules with `pip3` instead of `pip`.

Still not work in Jupyter notebook
