### ISSUE TITLE
Target isnt responding properly

### ISSUE THREAD

**Issue by soupnatzi** [s0md3v/XSStrike#63]
[?] Would you like to look for hidden parameters? [y/N] y
[+] Heuristics found a potentially valid parameter: q. Priortizing it.
[+] Heuristics found a potentially valid parameter: l. Priortizing it.
[~] Parameters checked: 29/97
[-] Target isn't responding properly.

**Comment by s0md3v** [comment]
Looks like the target has blacklisted you or has become unresponsive due to making too many requests.

**Comment by soupnatzi** [comment]
can i run the tool with tor?

**Comment by s0md3v** [comment]
XSStrike doesn't have inbuilt support for tor atm, you will need to find a workaround yourself.

**Comment by soupnatzi** [comment]
got it
