### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by SbIm** [s0md3v/XSStrike#66]
The program is terminated for unknow error, the output is 
`[?] Enter a url: Traceback (most recent call last): 
  File "./xsstrike", line 256, in <module>
    main() #This is the true start of the program
  File "./xsstrike", line 219, in main
    target = input('%s Enter a url: ' % que) 
EOFError
`
I've tried on both MacOS and kali system, anyone has similar problems please?

**Comment by s0md3v** [comment]
[XSStrike v3.0's code and workflow is totally different from v2.0 so the issue doesn't hold anymore.]
