### ISSUE TITLE
Please add colors module in core

### ISSUE THREAD

**Issue by tauh33dkhan** [s0md3v/XSStrike#67]
The colors module is removed from the core because of which i am not able to run this tool please update it

$ python xsstrike.py
Traceback (most recent call last):
  File "xsstrike.py", line 5, in <module>
    from core.colors import end, red, white, green, yellow, run, bad, good, info, que
ImportError: No module named colors

**Comment by tauh33dkhan** [comment]
config module is also missing.

**Comment by coIev** [comment]
you don't need those modules, just navigate to where XSStrike is installed and just type: python3 xsstrike (without the.py) and all should work fine

**Comment by s0md3v** [comment]
[XSStrike v3.0's code and workflow is totally different from v2.0 so the issue doesn't hold anymore.]

**Comment by xahon** [comment]
I have the same issue and that neither work with `python2.7` nor `python3`. If i type xsstrike without `.py` extension, it says `python2.7: can't open file 'xsstrike': [Errno 2] No such file or directory` as expected to be

**Comment by meinkonho** [comment]
without .py it can't run on termux
