### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by coIev** [s0md3v/XSStrike#73]
XSStrike throws an error when scanning this url: https://www.scalemates.com/ajax/searchac.php?term=array

### Steps to reproduce

python3 xsstrike.py -u https://www.scalemates.com/ajax/searchac.php?term=array

Waiting for it to scan, then error throws:

File "/home/meow/XSStrike/core/htmlParser.py", line 45, in htmlParser
    tag = re.search(r'\w+', goodTokens[num]).group() # finds the tag "inside" which input is refelcted
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xsstrike.py", line 182, in <module>
    singleTarget(target, paramData)
  File "xsstrike.py", line 134, in singleTarget
    occurences = htmlParser(response)
  File "/home/meow/XSStrike/core/htmlParser.py", line 47, in htmlParser
    tag = re.search(r'\w+', goodTokens[num - 1]).group() # finds the tag "inside" which input is refelcted
IndexError: list index out of range

![download](https://user-images.githubusercontent.com/44411392/47612728-acb1e500-da3d-11e8-8551-bb0fe6e8748b.png)

**Comment by s0md3v** [comment]
[Fixed]
