### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by soupnatzi** [s0md3v/XSStrike#79]
[1] 5861
[2] 5862
bash: --params: command not found
[2]+  Done                    date_day=30

am running kali linux

**Comment by soupnatzi** [comment]
ran an update 
python3 xsstrike.py --update

	XSStrike v3.0-beta

[~] Checking for updates
[+] XSStrike is up to date!

**Comment by s0md3v** [comment]
```
[1] 5861
[2] 5862
```
The above output shows that you forgot enclose the URL within double quotes (") and the URL had a Ampersand (&) which was treated as special character by bash.
So there's that.

Also, `--update` option has been disabled for now because XSStrike isn't stable yet.
