### ISSUE TITLE
The timeout parameter doesn't take any input

### ISSUE THREAD

**Issue by 0xInfection** [s0md3v/XSStrike#85]
The timeout parameter doesn't seem to take any input from the user due the mentioned `action='store_true'` parameter, which it actually should. See [this](https://github.com/s0md3v/XSStrike/blob/master/xsstrike.py#L50).

I have made a PR #86 fixing this. :D

**Comment by s0md3v** [comment]
XSStrike doesn't use the timeout at all, the timeout has been hardcoded as it's just a beta release and has not been polished for end users.
Take a look here:

https://github.com/s0md3v/XSStrike/search?q=timeout&unscoped_q=timeout

**Comment by 0xInfection** [comment]
Well, I guess then it needs to be polished. Otherwise there is no need for the `--timeout` parameter.

**Comment by s0md3v** [comment]
It will get polished once the core starts working as expected.
The main objective for now is to make the parsing and detection logic as accurate as possible.

**Comment by 0xInfection** [comment]
I commented out the extra code which is not needed at present.

**Comment by s0md3v** [comment]
It's written as intended, sorry.
