### ISSUE TITLE
ImportError: cannot import name 'fuzz'

### ISSUE THREAD

**Issue by nice9uy** [s0md3v/XSStrike#87]
Hii..
I have a problem with installation of xsstrike.
my error is ImportError: cannot import name 'fuzz' when i run xss strike
![screenshot at 2018-11-07 09-51-32](https://user-images.githubusercontent.com/25494182/48107607-defbe780-e272-11e8-8656-58d9b8ae92e7.png)

can you help me, whats wrong with this?

Thanks

**Comment by s0md3v** [comment]
`pip3 uninstall fuzzywuzzy && pip3 install fuzzywuzzy --no-cache-dir`
