### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by siza3x** [s0md3v/XSStrike#88]
why i get this plzz anyone help me!
root@kali:~/Desktop/xss/XSStrike# python3 xsstrike.py -u http://www.multan.gov.pk/files.php?id=1 

	XSStrike v3.0-beta

[~] Checking for DOM vulnerabilities
------------------------------------------------------------
1046 var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
1047 document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
------------------------------------------------------------
[+] Potentially vulnerable objects found
[-] WAF detected: Mod_Security
[!] Testing parameter: id
[!] Reflections found: 1
[~] Analysing reflections
[~] Generating payloads
Traceback (most recent call last):
  File "/root/Desktop/xss/XSStrike/core/generator.py", line 66, in generator
    script = scripts[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xsstrike.py", line 238, in <module>
    singleTarget(target, paramData)
  File "xsstrike.py", line 146, in singleTarget
    vectors = generator(occurences, response)
  File "/root/Desktop/xss/XSStrike/core/generator.py", line 68, in generator
    script = scripts[0]
IndexError: list index out of range

**Comment by s0md3v** [comment]
This issue has been fixed already which means you aren't using the latest version of XSStrike.

**Comment by siza3x** [comment]
I use the latest version of xsstrike.plzzzz fo something bro

**Comment by siza3x** [comment]
U can see the xsstrike version in the screenshot.that is v3.0 beta

**Comment by s0md3v** [comment]
I checked the the latest version against the target and it doesn't throw any error.
It takes just 7 seconds to clone a repo so better re-clone it next time before wasting someone's time.
You would have paid a lot if XSStrike wasn't free and here are you, asking stupid questions without co-operating.
