### ISSUE TITLE
Add option to not verify SSL certs

### ISSUE THREAD

**Issue by carstenhag** [s0md3v/XSStrike#97]
Tried to scan my application that's running on localhost that is running with a self-signed certificate, which I have not imported, got this:

`
Error: HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /ticket/create (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1045)')))
`

**Comment by s0md3v** [comment]
Can you please confirm that the patch works?
